<?php 
$data=array(
		'success'=>true,
		'result'=>array(
				array(
						'name'=>'Hot Girls Vietnam',
						'logo'=>'https://lh5.ggpht.com/1ewbqYAsupRTigswbTIoOUNr9AkKZkjwF-NbGdcxcRjo8eTlhO8WEi6-pTtxanTeofA=w300-rw',
						'link'=>'https://play.google.com/store/apps/details?id=sg.vinova.hotgirlsvietnam',
						'size'=>'1.5M',
						'provider'=>'Vinova Pte.Ltd',
						'_cl_platform'=>1,
						'discription'=>'Có trên 3000 hình ảnh HD của các cô gái sexy - Tự động cập nhật hình ảnh hàng ngày. Đây là ứng dụng bạn không nên bỏ qua bởi nó hoàn toàn miễn phí, thanh lịch, thiết kế đơn giản, tốc độ tải nhanh.'
				),
				array(
						'name'=>'Tử Vi Tình Yêu',
						'logo'=>'https://lh4.ggpht.com/aTBuvtZFmQUhdCCFbFwqiUVlIetykRXGUYyOJEdmv8oHKzD1Kh5hAMkUniBR0xZ0ZR4=w300-rw',
						'link'=>'https://play.google.com/store/apps/details?id=appinventor.ai_kohuru.Tuvi',
						'size'=>'1.6M',
						'provider'=>'Elden Tri Lee',
						'_cl_platform'=>1,
						'discription'=>'Trước khi dựng vợ gả chồng, ông bà ta thường đi xem thầy, con trai và con gái có hợp tuổi không? Thầy lấy tài liệu từ đâu. Sau đây là trích lược tài liệu cổ thư cũng có giá trị tham khảo. Nhưng đừng dựa vào đây mà các bạn đánh mất niềm tin vào tình yêu và cuộc sống, chúng ta không nên tin, chỉ tham khảo vì sao ông bà ta nói không hợp là do đâu? Xây dựng gia đình do chúng ta quyết định.'
				),
				array(
						'name'=>'Xray Scanner',
						'logo'=>'https://lh4.ggpht.com/uTB9-D55pqGSAsDEvnYrIq_PNa8R6NKS1MCCUD7iScyg7GYiojuFSVc8e-7XivcCi5Y=w300-rw',
						'link'=>'https://play.google.com/store/apps/details?id=us.porrassoft.xray',
						'size'=>'920K',
						'provider'=>'porrassoft',
						'_cl_platform'=>1,
						'discription'=>'Bạn có muốn để quét bàn tay của bạn với X-RAY? Được vui vẻ với XRAY SCANNER!
										Đây là một ứng dụng trò đùa để có được niềm vui và lừa bạn bè của bạn.'
				),
				array(
						'name'=>'2048 Number puzzle game',
						'logo'=>'https://lh4.ggpht.com/tnPMNQZ4vyFjflXlb-VaggJ0mw4ncnrYzgOgi2nVPuQEPmANDqH_uGPWc5KqfW77kQ=w300-rw',
						'link'=>'https://play.google.com/store/apps/details?id=com.estoty.game2048',
						'size'=>'4.9M',
						'provider'=>'Estoty Entertainment Lab',
						'_cl_platform'=>1,
						'discription'=>'Gây nghiện nhất phiên bản di động của 2048 trò chơi và trò chơi gần như hoàn hảo 2048 số câu đố cho Android! Khám phá thách thức sâu sắc đối với tâm trí của bạn!
						-Game-hướng dẫn
						Swipe để di chuyển gạch, khi hai gạch với các liên lạc cùng một số, họ hợp nhất thành một.
						Ví dụ: 2 +2 = 4 ... 4 +4 = 8 ... Khi một gạch 2048 được tạo ra, người chơi thắng..'
				)
		)
);

send_json($data);