<?php $this->headScript()->appendFile('/api_google_search_images.js');?>
<?php $item =  array('name' => 'ho va ten','avatar' => '/hoibinet.ico', 'id'=> '1');?>
<?php 
  //  $item = $this->item;
    $lu = Zend_Registry::get('user');
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<div class="row">
<div class="col-md-6">
<div class="item_profile">
  	<div class="title">
        <span><?php echo $item['name']?></span>
        <div class="clear"></div>
    </div>
    <div class="item_content">
    	<div class="col1">
        <div class="stuff_large">
            <div id="btn_set_default_avatar" class="btn_set_default_avatar"><button class="btn btn-primary btn-xs">Set avatar default</button></div>
        	<div id="btn_remove_avatar" class="btn_set_default_avatar" ><button class="btn btn-success btn-xs">Remove avatar</button></div>
        </div>
        <?php //echo $this->render('index/show-gallery.phtml')?>
        <div class="clear"></div>
        <div class="related">
        </div>
        </div>
        <div class="col2">
            <?php //echo $this->render('index/show-gallery.phtml')?>
        </div>
    	<div class="clear"></div>
    </div>
  </div>
<div class="viewmode"></div>
<a target='blank' href='/item/fake-gallery?id=<?php echo $item['id']?>'>fake gallery</a>
</div>
<div class="col-md-6">sadasd</div>
</div>
<div id="insertGallery">
	Get image from local: 
	<form id="upload-avatar" class="cl_ajax" action="/item/insert-gallery-image?id=<?php echo $item['id'];?>&_cl_ajax=1" method="post" enctype="multipart/form-data">
		<input type="file" name="path_local" />
        <input id="uploadLocal" class="btn btn-primary btn-xs" type="submit" value="Upload"/>
    </form>
 	<input type="text" id="path_local" name="path_local"/><input type="button" id="upload_local" value="Upload"/><br> 
	Get image from Google: 
	<input type="checkbox" checked="checked" value="google" id="google"/>
	Get image from Bing: 
	<input type="checkbox" checked="checked" value="bing"  id="bing"/>
	<input type="button" id="submit" value="Search"/>
	<input type="hidden" id="name" value="<?php echo $item['name'];?>"/>
	<input type="hidden" id="id" value="<?php echo $item['id'];?>"/>
</div>
<div id="googleSearch" class="api_search"></div>
<div id="bingSearch" class="api_search"></div>
<div id="waiting"><img src="/layouts/css/images/waiting.gif"/></div>
<div class="clear"></div>

<div class="topic_list">
</div>