<?php $keys = array(
    'remove', 'send_to_back', 'submitting','right_click_on_the_image_below_and_save_it_locally_on_your_computer',
    'this_application_does_not_support_Internet_Explorer!_Please_use_Firefox,_Chrome_or_Safari!','loading',
    'importing','invalid_image','please_set_URL_to_image','are_you_sure_you_want_to_clear_the_canvas','move','move_-_Click_and_drag',
    'set_color','decrease_size','increase_size','toggle_bold','clone_text','toggle_italic','click_here_to_change_text',
    'vertical_line','horizontal_line','please_write_your_title,description,text_and_click_submit_to_display_your_rage_comic_on_the_main_page',
    'drag_me_around!This_is_also_resizable','rotate_right','rotate_left','horizontal_flip','clone_object',
    'ready_to_submit','title','description','importing','submit','story_title'     ///    
);?>
var rageTranslations = {
<?php foreach ($keys as $k):?>
    '<?php echo $k?>' : '<?php echo t($k);?>',
<?php endforeach;?>    
};

