<div class="panel panel-default">
  <div class="panel-heading" style="padding-top:5px; padding-bottom: 5px;">
    <h3 class="panel-title">  <?php echo t("most_active_user",1);?></h3>
  </div>
  <div class="panel-body">
<div class="tabbable">
  <ul class=" topUsersSort topUsersSortHome nav nav-tabs">
    <li class="active"><a href="#pane1" data-toggle="tab"><?php echo t("weekly",1);?></a></li>
    <li><a href="#pane2" data-toggle="tab"><?php echo t("monthly",1);?></a></li>
    <li><a href="#pane3" data-toggle="tab"><?php echo t("all",1);?></a></li>
  </ul>
         
    <div class="clear">
    </div>
  
  <div class="tab-content">
    <div id="pane1" class="tab-pane active">
      <div id="top_user:7">
           		 <div id="topUserContent">    
           		 	<div class="topUsers">
           		 	<?php foreach ($this->top7 as $row){?>
           		 	    <div class="item"> 
                        <a style="text-decoration: none;" href="/user/<?php echo $row['uiid']?>">
                          <?php 
                            if($row['avatar'] == '')
                                $row['avatar'] = ASSETS_CDN . "img/hoibinet.jpg";
                            ?>
                             <img src="<?php  echo $row['avatar'];?>">
                            <div class="info">
                                <span class="name user-link"><?php echo $row['name']?></span> 
                                <i class="<?php echo get_icon('thumbs-up');?>"> </i>
                                <span class="likes"><?php echo $row['karma']?></span>
                            </div>	
                        </a>
                    </div>  
           		 	<?php }?>
           		   		</div>
                	<div class="clear">
                		</div>
            	</div>
            </div>
    </div>
    <div id="pane2" class="tab-pane">
   
             <div id="top_user:30" style="display:block">
           		 <div id="topUserContent">    
           		 	<div class="topUsers">
           		 	<?php foreach ($this->top30 as $row){?>
           		 	    <div class="item">
                        <a style="text-decoration: none;" href="/user/<?php echo $row['uiid']?>">
                            <?php 
                            if($row['avatar'] == '')
                                $row['avatar'] = ASSETS_CDN . "img/hoibinet.jpg";
                            ?>
                             <img src="<?php  echo $row['avatar'];?>">
                            <div class="info">
                                <span class="name user-link"><?php echo $row['name']?></span> 
                                <i class="<?php echo get_icon('thumbs-up');?>"> </i>
                                <span class="likes"><?php echo $row['karma']?></span>
                            </div>
                        </a>
                    </div>  
           		 	<?php }?>
           		   		</div>
                	<div class="clear">
                		</div>
            	</div>
            </div>
    </div>
    <div id="pane3" class="tab-pane">
      <div id="top_user:all" style="display:block">
           		 <div id="topUserContent">    
           		 	<div class="topUsers">
           		 	<?php foreach ($this->topAll as $row){?>
           		 	    <div class="item">
                        <a  style="text-decoration: none;" href="/user/<?php echo $row['uiid']?>">
                        <?php 
                            if($row['avatar'] == '')
                                $row['avatar'] = ASSETS_CDN . "img/hoibinet.jpg";
                            ?>
                             <img src="<?php  echo $row['avatar'];?>">
                            <div class="info">
                                <span class="name user-link"><?php echo $row['name']?></span> 
                                <span class="likes">
                                 <i class="<?php echo get_icon('thumbs-up');?>"> </i>
                                <?php echo $row['karma']?></span>
                            </div>
                        </a>
                    </div>  
           		 	<?php }?>
           		   		</div>
                	<div class="clear">
                		</div>
            	</div>
            </div>
    </div>
  </div><!-- /.tab-content -->
</div><!-- /.tabbable -->
</div>
</div>