<?php
	$categories = $this->categories;
	$row = $this->row;
    $hp_product = $this->hp_product;
	$hp_product = Dao_Node_Product::getInstance()->getStandedProduct($hp_product);
?>
<section class="main row">
	<div class="twelve columns">
		<section id="main" class="module">
			<div id="content" class="module-body">
				<div id="deal_content" class="three-col">
					<div id="deal_content" class="three-col">
						<div id="js-page-header" class="page_header">
							<div>
								<h2 class="browse-title-heading"> 
									<a href="<?php echo category_link($row);?>">
									<?php echo $row['name'];?></a> </h2>
							</div>
							<div class="dotted-line"></div>
						</div>
						
						<div class="main module">
							<div class="row">
								<div class="three columns">
									<div id="left-nav-categories">
										<?php if(count($categories) > 0):?>
											<ul>
												<?php foreach ($categories as $cate):?>
													<li> 
														<a href="<?php echo category_link($cate['detail']);?>"> 
															<?php echo $cate['detail']['name'];?>
															<span class="counter">
																<?php $count = isset($cate['products']) ? count($cate['products']) : 0;?>
																(<?php echo $count;?>)</span> 
															</a> </li>
												<?php endforeach;?>
											</ul>
										<?php endif;?>
									</div>
								</div>
								
								<div class="nine columns">
									<div id="featured">
								        <figure class="hero-deal">
										  <a href="<?php echo node_link('product', $hp_product);?>" title='<?php echo $hp_product['name'];?>'>
										   <img src="<?php
											  $url = STATIC_GT . $hp_product['images'];
								              if(!url_exists($url)){
								              	$url = default_avatar('product');
								              }
								              
								              echo $url;
							                   ?>"
							                   <?php  /*Giup hien thi phan giua cua anh*/
							                   /*(Filled image widget new|hot|vote)*/
							                   if(url_exists($url)){
									               list($width, $height) = getimagesize($url);
									               $heightFilledImage = 422;//height class filedImage img
													$widthFilledImage = 702;
									                
									                //Get height (chieu dai thuc cua anh ty le
									                // voi chieu dai cua khung chua anh)
									                /*
													$heightFilledImageNew = $widthFilledImage * $height/ $width;
									                
									                $gap = ($heightFilledImageNew - $heightFilledImage)/2;
									                if($gap > 0){
									                	echo "style = 'margin-top: -{$gap}px'";
									                }*/
									                
									                $widthFilledImageNew = $heightFilledImage * $width/$height;
									                
									                $gap = ( $widthFilledImage - $widthFilledImageNew)/2;
									                if($gap > 0){
									                	echo "style = 'margin-left: {$gap}px'";
									                }
											   }
								                ?>>
										  </a>
										  <figcaption>
										    <h2>
										      <a href="<?php echo node_link('product', $hp_product);?>" 
										      	title='<?php echo $hp_product['name'];?>'><?php echo $hp_product['name'];?></a>
										    </h2>
										
										    <div class="deal-metadata">
										    <?php /*
										        <p style="word-wrap: break-word;" 
										        	class="merchant-name should-truncate">
										        	<?php echo $hp_product['category']?></p>
										        <p class="meta-divider">|</p>
										    */?>
										        <p style="word-wrap: break-word;" class="deal-location should-truncate">
										        	<?php echo $hp_product['counter']['buy'];?> đã mua</p>
										    </div>
										
										    <p class="deal-price">
										        <s class="original-price" title='Giá ban đầu'>
										        <?php echo show_money($hp_product['origin_price']);?>₫</s>
										        <?php echo show_money($hp_product['deal_price']);?>₫
										    </p>
										    <div class="view-deal">
										      <a href="<?php echo node_link('product', $hp_product);?>" class="btn-buy">Xem chi tiết</a>
										    </div>
										  </figcaption>
										</figure>
								
								      </div>
								</div>
							</div>
							
						    <?php if(count($categories) > 0):?>
							  <div id="channel-deals">
							  	<?php foreach ($categories as $cate):?>
							  	<?php $products = isset($cate['products']) ? $cate['products'] : array();?>
								  	<?php if(count($products) > 0):?>
									  <section class="deal-pack row pad-row">
										  <div class="section-head">
										      <a href="<?php echo category_link($cate['detail'])?>">
										      	<h2><?php echo $cate['detail']['name'];?></h2></a>
										  </div>
										  <div class="block-grid three-up">
								  			<?php foreach ($products as $product):?>
										  		<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
										      <figure class="deal-card">
										        <a href="<?php echo node_link('product', $product);?>">
										          <img src="
										        <?php
									 				  $url = STATIC_GT . $product['images'];
										              if(!url_exists($url)){
										              	$url = default_avatar('product');
										              }
										              echo $url;
									                   ?>"
									                   <?php  /*Giup hien thi phan giua cua anh*/
									                   /*(Filled image widget new|hot|vote)*/
										               list($width, $height) = getimagesize($url);
										               $heightFilledImage = 187;//height class filedImage img
													   $widthFilledImage = 300;
										                
										                //Get height (chieu dai thuc cua anh ty le
										                // voi chieu dai cua khung chua anh)
															/*
															$heightFilledImageNew = $widthFilledImage * $height/ $width;
											                
											                $gap = ($heightFilledImageNew - $heightFilledImage)/2;
											                if($gap > 0){
											                	echo "style = 'margin-top: -{$gap}px'";
											                }*/
											                
											                $widthFilledImageNew = $heightFilledImage * $width/$height;
											                
											                $gap = ($widthFilledImage - $widthFilledImageNew)/2;
											                if($gap > 0){
											                	echo "style = 'margin-left: {$gap}px'";
											                }?>">
										          <figcaption>
										            <p style="word-wrap: break-word;" class="deal-title should-truncate">
										            	<?php echo $product['name'];?></p>
										            <p style="word-wrap: break-word;" class="merchant-name should-truncate">
										       		     <?php echo $product['category']['name'];?></p>
										            <p style="word-wrap: break-word;" class="deal-location should-truncate">
										          		 <?php echo $product['counter']['buy'];?> đã mua</p>
										            <p class="deal-price">
										                <s class="original-price">
										                <?php echo show_money($product['origin_price']);?>₫</s>
										        	    <?php echo show_money($product['deal_price']);?>₫
										            </p>
										          </figcaption>
										        </a>
										      </figure>
								   		    <?php endforeach;?>
										  </div>
										</section>
								  	<?php endif;?>
							     <?php endforeach;?>
							   </div>
						    <?php endif;?>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</section>