<div class='row'>
<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='col-md-12'>
<?php echo $this->render('index/navbar.phtml');?>
</div>
</div>

<div class='row'>
<div class='col-md-2'>
    <div class='search_form well well-shallow'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-10'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<h3>Kết quả tìm kiếm</h3>
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/category/bulk-delete" id='bulk-delete' class="cl_ajax btn btn-xs btn-danger">
    	Xóa mục đã chọn</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<th>Tên Chuyên mục</th>
        			<th title='Nếu chọn level 1 và đã được duyệt, chuyên mục sẽ được hiển thị
        			trên menu trang chủ' class='btn btn-sm btn-default'>Level</th>
        			<th>Trạng thái</th>
        			<th>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<?php $row['level'] = isset($row['level']) ? $row['level'] : 1;?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<td><a href="<?php echo node_link('category',$row);?>"><?php echo $row['name'];?></a>
        				(<?php echo $row['iid'];?>)
        			</td>
        			<td>
                        <div class="btn-group">
        			    	<a href="/category/update?id=<?php echo $row['id'];?>&level=1&_cl_step=is_level"
        			    	class="btn <?php if($row['level']==1):?>btn-primary<?php else: ?>btn-default<?php endif;?> btn-xs cl_ajax" 
        			    	_cl_get_metadata="active_button_group"
        			    	title='Nếu chọn level 1 và đã được duyệt, chuyên mục sẽ được hiển thị
        					trên menu trang chủ' class='btn btn-sm btn-default'> Is Level 1 </a>
        			    	<a href="/category/update?id=<?php echo $row['id'];?>&level=2&_cl_step=is_level"
        			    	class="btn btn-xs <?php if($row['level']== 2):?>btn-primary<?php else: ?>btn-default<?php endif;?>	 cl_ajax" 
        			    	_cl_get_metadata="active_button_group"> UnLevel 1</a>
        			    </div> 
        			</td>
        			<td>
        			<?php
        				$row['status'] = isset($row['status']) ? $row['status'] : 'queued';
        			?>
                        <div class="btn-group">
        			    	<a href="/category/update?id=<?php echo $row['id'];?>&status=queued&_cl_step=status"
        			    	class="btn btn-xs <?php if($row['status']=='queued'):?> btn-primary <?php else:?> btn-default <?php endif;?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group"> Đang chờ </a>
        			    	<a href="/category/update?id=<?php echo $row['id'];?>&status=approved&_cl_step=status"
        			    	class="btn btn-xs <?php if($row['status']=='approved'):?> btn-primary <?php else:?> btn-default <?php endif;?> cl_ajax"
        			    		 _cl_get_metadata="active_button_group"> Đã duyệt</a>
        			    </div> 
        			</td>
        			
        			<td>
        				<a href="/category/update?id=<?php echo $row['id']?>" class="btn btn-xs btn-default">
        					<i class="icon-edit"></i> Sửa</a>
        				<a href="/category/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" _cl_get_metadata="remove_my_parent:2"
        					_cl_ajax_confirm='Are you sure you want to permanently delete this item?'
        					>
        					<i class="icon-remove"></i> Xóa
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No category found</h3>
    <?php endif;?>
</div>

</div>