<div class='row'>
<?php echo sand_dev_info_phtml(__FILE__);?>

<?php $page = Zend_Registry::get('page');?>
<div class='col-md-12'>
<?php echo $this->render('index/navbar.phtml');?>
</div>
<div class='col-md-6'>
<?php if ($page == 'related/index/new'):?>
<h1> Tạo so sánh giá mới</h1>
<?php else:?>
<h1> Sửa so sánh giá</h1>
<?php endif;?>
<?php $this->form->setAttrib('class', 'cl_ajax');?>
<?php echo $this->form;?>
</div>
<div class='col-md-6'>
<a href="#" id="preview_post_btn" class='btn btn-primary'>Preview</a>
    <hr/>
    <div id='preview_area'>
    </div>
</div>
</div>