<div class='row'>
<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='col-md-12'>
<?php echo $this->render('index/navbar.phtml');?>
</div>
</div>

<div class='row'>
<div class='col-md-2'>
    <div class='search_form well well-shallow'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-10'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<h3>Kết quả tìm kiếm</h3>
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/related/bulk-delete" id='bulk-delete' 
    		class="cl_ajax btn btn-xs btn-danger">Xóa mục đã chọn</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<th>Hình ảnh</th>
        			<th>Mô tả sản phẩm</th>
        			<th>Nơi bán</th>
        			<th>Giá bán</th>
        			<th>Status</th>
        			<th>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<?php $avatar = (isset($row['images']) && $row['images'] != '') ? $row['images'] : default_avatar('related');?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<td ><img src='<?php 
							$url = STATIC_GT . $row['images'];
					        if(!url_exists($url)){
					        	$url = default_avatar('product');
					        }
					        echo $url;           
					        ?>' 
						width='85px'/></td>
					<td >
						<span style='font-weight: bold; text-align: center;'>
						<a href='<?php echo node_link('related', $row);?>'><?php echo $row['name']?></a></span><br>
						<?php echo $row['description'];?>
						</td>
					<td ><span style='font-weight: bold; text-align: center;'>
						<?php echo $row['brand'];?></span><br>
						<?php $url = STATIC_GT . $row['avatar_brand'];
					        if(url_exists($url)):?>
						<img src='<?php echo $url;?>'/>
					        <?php endif;?>
						</td>
					<td >
						<span style='font-weight: bold; text-align: center;'>
						<?php echo show_money($row['origin_price']);?></span><br>
						<a href="<?php echo $row['link'];?>" target='_blank' 
							class="btn btn-primary btn-xs" style='font-size: 10px;'>
          							Đến nơi bán
        							</a>
								</td>
        			<td>
                        <div class="btn-group">
        			    	<a href="/related/update?id=<?php echo $row['id'];?>&status=queued&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='queued') echo 'active';?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group"> Đang chờ </a>
        			    	<a href="/related/update?id=<?php echo $row['id'];?>&status=approved&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='approved') echo 'active';?> cl_ajax"
        			    		 _cl_get_metadata="active_button_group"> Đã duyệt</a>
        			    </div> 
        			</td>
        			
        			<td>
        				<a href="/related/update?id=<?php echo $row['id']?>&product__id=<?php echo $row['product']['id'];?>" class="btn btn-xs btn-default">
        					<i class="icon-edit"></i> Sửa</a>
        				<a href="/related/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" _cl_get_metadata="remove_my_parent:2"
        					_cl_ajax_confirm='Are you sure you want to permanently delete this item?'
        					>
        					<i class="icon-remove"></i> Xóa
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No related found</h3>
    <?php endif;?>
</div>

</div>