<?php $page = Zend_Registry::get('page');?>
<ul class='nav nav-pills'>
	<li <?php if ($page == 'ad/index/new') echo "class='active';"?>><a href="/ad/new">
		Tạo mới</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'ad/index/update') echo "class='active';"?>>
		<a href="/ad/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>"">Cập</a></li>
	<?php endif;?>    
	<li <?php if ($page == 'ad/index/search') echo "class='active';"?>><a href="/ad/search">Tìm kiếm</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'ad/index/view') echo "class='active';"?>>
		<a href="/ad/view?id=<?php if (isset($this->row['id'])) echo "" . $this->row['id'];?>">Xem chi tiết</a></li>
	<?php endif;?>
</ul>
<div class='separator'></div>
