<div class='col-md-12'>
<?php echo $this->render('index/navbar.phtml');?>
</div>

<div class='col-md-12'>
    <div class='search_form well'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-12'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<h3>Ad List</h3>
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/<?php echo $this->module?>/bulk-delete" class="cl_ajax btn btn-mini">Delete</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<th>ID</th>
        			<th>Name</th>
        			<th>Status</th>
        			<th>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<td><?php echo Cl_Utility::charBreadcumb($row['id'], 8);?>...</td>
        			<td><a href="<?php echo node_link('ad',$row);?>"><?php echo $row['name'];?></a></td>
        			<td>
                        <div class="btn-group">
        			    	<a href="/ad/update?id=<?php echo $row['id'];?>&status=queued&_cl_step=status"
        			    	class="btn btn-primary btn-mini <?php if($row['status']=='queued') echo 'active';?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group"> Queued </a>
        			    	<a href="/ad/update?id=<?php echo $row['id'];?>&status=approved&_cl_step=status"
        			    	class="btn btn-primary btn-mini <?php if($row['status']=='approved') echo 'active';?> cl_ajax" _cl_get_metadata="active_button_group"> Approved</a>
        			    </div> 
        			</td>
        			
        			<td>
        				<a href="/<?php echo $this->module;?>/update?id=<?php echo $row['id']?>" class="btn btn-mini"><i class="<?php echo get_icon('edit');?>"></i>Edit</a>
        				<a href="/<?php echo $this->module;?>/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-mini cl_ajax" _cl_get_metadata="remove_my_parent:2">
        					<i class="<?php echo get_icon('edit');?>"></i>Delete
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No ad found</h3>
    <?php endif;?>
</div>
