<div class='row'>
<?php echo sand_dev_info_phtml(__FILE__);?>

<?php $page = Zend_Registry::get('page');?>
<div class='col-md-12'>
<?php echo $this->render('index/navbar.phtml');?>
</div>
<div class='col-md-6'>
<?php if ($page == 'product/index/new'):?>
<h1> Tạo sản phẩm mới</h1>
<?php else:?>
<h1> Cập nhật sản phẩm mới</h1>
<?php endif;?>
<?php //v($this->form);?>
<?php $this->form->setAttrib('class', 'cl_ajax form-inline');?>
<?php $this->form->setAttrib('id', 'new-product')?>
<?php echo $this->form;?>
</div>
<div class='col-md-6'>
<a href="#" id="preview_post_btn" class='btn btn-primary'>Xem trước</a>
    <hr/>
    <div id='preview_area'>
    </div>
</div>
</div>
<?php $this->inlineScript()->captureStart();?>

	$(document).ready(function(){
	 	$('.datetimepicker').datetimepicker({
             timepicker:false,
             format:'d/m/Y'
        });
    });
<?php $this->inlineScript()->captureEnd();?>