<?php
   $form = $this->form;
?>
<div class="main row">
  <section class="twelve columns">
      <section class="module">
        <div class="module-body">
          <div id="account-billing-info">
          	<div class="limited-time" style='border-top: medium none;'>
		        <span class="no-counter">
		        	Cám ơn quý khách đã góp ý kiến để xây dựng trang web Giasomot.vn<br><br>
		        	Giasomot.vn sẽ cố gắng hoàn thiện để phục vụ khách hàng một cách tốt nhất và thuận tiện nhất
	        	</span>
		    </div>
		    
		    <div style='min-height: 200px;'></div>
          </div>
        </div>
      </section>
  </section>
</div>