<div class="main row">
	<div class="twelve columns">
		<div class="module">
			<div class="module-body">
				<h1 class="section-title">Chính sách đổi, trả hàng</h1>
					<h2 style="color: red;">I. MỤC ĐÍCH:</h2>
					Nhằm đảm bảo quyền lợi người tiêu dùng, nâng cao chất lượng dịch vụ sau bán hàng, Công ty Giasomot sẽ hỗ trợ Quý khách đổi sản phẩm mới cùng loại nếu sản phẩm gặp sự cố không thể khắc phục được ngay (do lỗi kỹ thuật của nhà sản xuất). Sản phẩm chỉ được đổi khi đáp ứng đầy đủ các điều kiện sau dưới đây:
					<h2 style="color: red;">II. ĐIỀU KIỆN ÁP DỤNG:</h2>
					<h3>1. Thời gian đổi hàng:</h3>
					<p>
					Sản phẩm được đổi trong khoảng thời gian kể từ khi giao hàng như sau:
					</p>
					- Điện tử, Điện lạnh, Máy tính xách tay, Máy tính để bàn, Màn hình máy tính:  7 ngày
					<br>
					- Gia dụng: 3 ngày
					<br>
					- Viễn thông:  2 ngày
					<br>
					- Kỹ thuật số, Phụ kiện IT: 24 giờ
					<br>
					(Lưu ý: điều kiện này không áp dụng cho các sản phẩm: Điều hòa nhiệt độ, Bình nóng lạnh, Tủ đông, Máy in, Máy fax)
					 <br>
					<h3>2. Sản phẩm phải còn nguyên tem niêm phong của Giasomot hoặc của nhà sản xuất.</h3>
					<h3>3. Sản phẩm được xác định bị lỗi kỹ thuật bởi các Kỹ thuật viên của Giasomot hoặc của nhà sản xuất.</h3>
					<h3>4. Sản phẩm nhận lại phải còn nguyên vẹn vỏ thùng, xốp và đầy đủ các phụ kiện kèm theo, quà khuyến mãi (nếu có)…</h3>
					<h3>5. Sản phẩm nhận lại không bị lỗi hình thức (trầy xước, vỡ, móp méo, ố vàng,…)</h3>
					<h3>6. Sản phẩm khi nhận lại phải có đầy đủ các chứng từ kèm theo như (chứng từ mua hàng, hóa đơn VAT nếu có, phiếu bảo hành, sách hướng dẫn, catalogue…)</h3>
					 
					<h2 style="color: red;">III. TRƯỜNG HỢP KHÔNG CHẤP NHẬN ĐỔI TRẢ:</h2>
					 
					<h3>1.  Quý khách muốn thay đổi chủng loại, mẫu mã nhưng không thông báo trước.</h3>
					<h3>2.  Quý khách vận hành không đúng chỉ dẫn gây hỏng hóc sản phẩm.</h3>
					<h3>3.  Quý khách không thực hiện các quy định theo yêu cầu để được hưởng chế độ bảo hành (ví dụ không gửi phiếu bảo hành về đúng nơi quy định trong thời gian quy định)</h3>
					<h3>4.  Quý khách tự làm ảnh hưởng đến tình trạng bên ngoài sản phẩm như rách bao bì, trầy, xước, vỡ,…</h3>
					<h3>5.  Sản phẩm đã được Quý khách kiểm tra và ký xác nhận tình trạng nhưng sau đó Quý khách yêu cầu đổi trả hàng hóa vì lý do lỗi về ngoại quan (trầy xước, móp méo, ố vàng, vỡ…).</h3>
					 
					<h2 style="color: red;">IV. QUY TRÌNH XỬ LÝ THỦ TỤC ĐỔI TRẢ HÀNG:</h2>
					<h3>1. Quý khách liên hệ trực tiếp với Trung tâm bảo hành của Hãng hoặc thông qua Trung chăm sóc khách hàng của Công ty Giasomot. Sau khi có Giấy xác nhận tình trạng với nội dung hàng hóa hư hỏng do lỗi kỹ thuật không thể sửa chữa được ngay, việc đổi hàng sẽ được thực hiện theo đúng quy định của Công ty Giasomot và của nhà sản xuất hoặc Trung tâm bảo hành được ủy quyền của nhà sản xuất.</h3>
					<h3>2. Quy trình xử lý thủ tục đổi hoặc trả hàng được thực hiện trong vòng 7 (bảy) ngày tính từ ngày nhận đủ thông tin và các giấy tờ theo quy định từ phía khách hàng.</h3>
					<h3>3. Liên hệ làm thủ tục đổi trả hàng:</h3>

			</div>
		</div>
	</div> 
</div>