<div class="main row">
	<div class="twelve columns">
		<div class="module">
			<div class="module-body">
				<h1 class="section-title">Chính sách vận chuyển hàng</h1>
					<h2 style="color: red;">I. CHÍNH SÁCH GIAO NHẬN, LẮP ĐẶT SẢN PHẨM ĐIỆN MÁY: ĐIỆN TỬ, ĐIỆN LẠNH, GIA DỤNG</h2>
					<h3>1. MỤC ĐÍCH:</h3>
					Quy định chính sách giao nhận, lắp đặt với mong muốn tạo ra các giá trị gia tăng cho sản phẩm khi khách hàng mua sắm tại Giasomot.
					<h3>2. PHẠM VI ÁP DỤNG:</h3>
					<h4>2.1 Đối tượng áp dụng:</h4>
					- Tất cả các khách hàng mua sản phẩm điện tử, điện lạnh, gia dụng tại Giasomot.
					<h4>2.2 Khu vực áp dụng:</h4>
					Giao nhận miễn phí các khu vực sau:<br>
					- Thành phố Hà Nội và các tỉnh: Bắc Ninh, Hải Dương, Vĩnh Phúc, Hưng Yên, Thái Nguyên, Ninh Bình, Hà Nam, Việt Trì, Nam Định, Hải Phòng, Bắc Giang. . . Chính sách vận chuyển miễn phí dưới 200km áp dụng cho đơn hàng điện tử, điện lạnh, gia dụng trị giá từ 1,5 triệu đồng trở lên.
					<h3>3. NỘI DUNG:</h3>
					<h4>3.1 Dịch vụ giao nhận sản phẩm:</h4>
					- Giasomot thực hiện dịch vụ giao nhận miễn phí tận nhà cho khách hàng ở các khu vực được quy định tại mục 2.2  với các đơn hàng trị giá từ 1.5 triệu đồng trở lên.
					<br>
					- Giasomot sẽ giao hàng trong vòng 24 giờ nếu phạm vi giao hàng ≤ 30km tính từ các siêu thị của Giasomot, riêng đơn hàng mua Online sẽ được giao hàng trong vòng 2 giờ đối với các đơn hàng có giá trị từ 1 triệu đồng trở lên.
					<br>
					- Giasomot sẽ giao hàng trong vòng 05 - 07 ngày nếu phạm vi giao hàng từ 30km đến 200km tính từ các trung tâm của Giasomot.
					<br>
					- Trước khi vận chuyển, bộ phận giao nhận sẽ liên lạc với Quý khách hàng để hẹn thời gian, địa điểm cụ thể để giao hàng cho Quý khách hàng.
					<br>
					- Thời gian giao hàng và lắp đặt: từ 8h30 đến 21h30 tất cả các ngày trong tuần.
					<br>
					<h4>3.2 Dịch vụ lắp đặt sản phẩm:</h4>
					- Công ty thực hiện việc lắp đặt sản phẩm tại nhà theo yêu cầu của khách hàng.
					<br>
					- Khách hàng sẽ thanh toán chi phí công lắp đặt, vật tư sử dụng thực tế theo “Bảng giá cung cấp vật tư, dịch vụ giao nhận, lắp đặt” sau khi khách hàng đã được hưởng tất cả các hình thức khuyến mại của công ty tại thời điểm mua hàng.
					<br>
					<font style="color: red;">Lưu ý:</font>
					<br>
					Đối với sản phẩm Tivi LCD: Khi khách hàng mua tivi kèm theo giá treo, công ty sẽ tặng công lắp đặt. Đối với các trường hợp khác công ty chỉ giao nhận chứ không lắp đặt miễn phí..
					 
					<h2 style="color: red;">II. CHÍNH SÁCH GIAO NHẬN, LẮP ĐẶT SẢN PHẨM KỸ THUẬT SỐ: THIẾT BỊ VIỄN THÔNG, THIẾT BỊ GIẢI TRÍ,
					THIẾT BỊ TIN HỌC</h2>
					<h3>1. MỤC ĐÍCH:</h3>
					Hỗ trợ khách hàng dịch vụ giao nhận, lắp đặt, cài đặt nhằm tạo ra các giá trị gia tăng cho sản phẩm khi khách hàng mua sắm tại Giasomot.
					<br>
					<h3>2. PHẠM VI ÁP DỤNG:</h3>
					<h4>2.1 Đối tượng áp dụng:</h4>
					Tất cả các khách hàng mua sản phẩm thiết bị tin học, thiết bị giải trí, kỹ thuật số, thiết bị viễn thông tại Giasomot.
					<br>
					<h4>2.2 Khu vực áp dụng:</h4>
					Thành phố Hà Nội, trong phạm vi 30km tính từ các siêu thị của Giasomot.
					<h3>3. NỘI DUNG:</h3>
					- Công ty sẽ giao hàng trong vòng 24 giờ kể từ khi khách hàng đặt hàng.
					<br>
					- Trường hợp khách hàng có nhu cầu lắp đặt, cài đặt tại thời điểm giao nhận sản phẩm: công ty sẽ phục vụ theo Phụ lục chính sách đính kèm.
					<br>
					- Trường hợp khách hàng tự lắp đặt/ cài đặt/ sản phẩm (đối với thiết bị tin học và thiết bị viễn thông): Khách hàng tự chịu trách nhiệm về kỹ thuật cài đặt/ lắp đặt cũng như mọi rủi ro, tổn thất, thiệt hại liên quan đến sản phẩm và con người như: rơi rớt làm hư hỏng sản phẩm, rơi rớt gây nguy hiểm đến tính mạng…
					<br>
					- Giasomot chỉ cài đặt các phầm mềm tin học có bản quyền. Giasomot chỉ hỗ trợ cài đặt hình, nhạc, chuông, games, … từ các trang web chính thức (có đăng ký bản quyền theo luật định).
					<br>
					- Giasomot chưa phục vụ giao hàng ngoài TP Hà Nội. Khi có nhu cầu, khách hàng có thể sử dụng dịch vụ giao nhận, cài đặt, lắp đặt của Giasomot theo Phụ lục Bảng giá dịch vụ giao nhận, lắp đặt, cài đặt. Trong trường hợp các vật tư khách hàng tự mua hoặc có sẵn, khách hàng tự chịu trách nhiệm về mọi rủi ro, tổn thất, thiệt hại liên quan đến sản phẩm và con người như: chất lượng vật tư không đảm bảo dẫn đến rơi rớt làm hư hỏng sản phẩm, rơi rớt gây nguy hiểm đến tính mạng … 
					<br>
					- Giasomot chưa phục vụ dịch vụ công xây dựng (khoan mặt bàn, lắp ráp bàn ghế, móc treo máy chiếu, ...).Khách hàng tự thuê ngoài hoàn tất các hạng mục, vật dụng cần thiết trước khi đề nghị Giasomot lắp đặt sản phẩm tin học.
					<br>			
			</div>
		</div>
	</div> 
</div>