<div class="main row">
	<div class="twelve columns">
		<div class="module">
			<div class="module-body">
				<h1 class="section-title">Quy trình đặt cọc </h1>
					   <h3>1, Dưới 20km không phải đặt cọc với tất cả các mặt hàng<br></h3>
					   <h3>2, Đối với địa điểm cách Tây Sơn - Đống Đa lớn hơn 20km<br> </h3>
					   	<font color='red'>Lưu ý</font> :
						Thiết bị viễn thông, thiết bị giải trí, thiết bị tin học chỉ vận chuyển dưới 30 km<br>
					   <h3>3, Với đơn hàng nhỏ hơn 2tr đồng đặt cọc 20% giá trị đơn hàng làm tròn lên trên 10 nghìn đồng đối với tất cả các mặt hàng.<br></h3>
					    &nbsp;&nbsp;&nbsp;Ví dụ:<br>
						120.000 đặt cọc 20% <br>
						590.000 đặt cọc 20%<br>
					   <h3>4, Đối với đơn hàng lớn hơn 2tr đồng đặt cọc 10%<br></h3>
					    &nbsp;&nbsp;&nbsp;Ví dụ:<br>
						2.100.000 đặt cọc 10% = 210.000<br>
					   <h3>5, Một số lưu ý:<br></h3>
					    &nbsp;&nbsp;&nbsp;Khi đặt hàng, Quý khách cần phải điền đầy đủ và chính xác các thông tin theo yêu cầu để tạo điều kiện thuận lợi 
					    cho Trung tâm Thương Mại Điện Tử Giá Số Một  trong việc xử lý và thực hiện đơn hàng. 
					    Nếu trường hợp không cung cấp đầy đủ thông tin hoặc thông tin không đúng chúng tôi có quyền hủy bỏ 
					    đơn hàng mà không cần báo trước cho quý khách. Nếu quý khách có bất cứ khó khăn nào trong việc mua 
					    hàng trên mạng hoặc trang web bị lỗi, hoặc quý khách không biết cách hoặc có thắc mắc nào xin vui 
					    lòng gọi trực tiếp bộ phận chăm sóc khách hàng (Hotline 0943.959.698)  để được nhân viên chúng tôi 
					    tư vấn tận tình.<br>
						&nbsp;&nbsp;&nbsp;Trước khi giao hàng nhân viên bán hàng của chúng tôi sẽ gọi lại để xác nhận thông tin nơi nhận hàng,
						thông tin khách hàng. Chúng tôi sẽ không chịu bất cứ trách nhiệm nào nếu quý khách cung 
					    cấp thông tin sai lệch dẫn đến mất hàng hoặc quý khách phải chịu hoàn lại chi phí giao nhận 
					 	cho chúng tôi nếu phải giao lần thứ 2 trở đi do quý khách cung cấp thông tin sai lệch 
						không đồng nhất.
			</div>
		</div>
	</div> 
</div>