<?php $row = $this->row;?>
<div class="main row">
	<div class="twelve columns">
		<div class="module">
			<div class="module-body">
				<h1 class="section-title">Cảm ơn khách hàng</h1>
					Cám ơn Quý khách đã gửi thông tin liên hệ hợp tác. Chúng tôi sẽ liên hệ lại với Quý khách trong thời gian sớm nhất<br>
					<br>Dưới đây là thông tin liên hệ của quý vị:<br>
					Họ và tên: <br>
					Điện thoại*: <br>
					Email*: <br>
					Tên Doanh nghiệp: <br> 
					Tỉnh/Thành phố: <br>
					<div style='min-height: 400px;'> </div>
			</div>
		</div>
	</div> 
</div> 