<div class="main row">
	<div class="twelve columns">
		<div class="module">
			<div class="module-body">
				<h1 class="section-title">Về chúng tôi </h1>
					 <h2>Nhiệm vụ :</h2>
					
					<p>• Mang đến cho khách hàng sản phẩm điện máy, công nghệ giá tốt nhất với chất lượng và 
					
					dịch vụ hoàn hảo nhất.</p>
					
					<h2>Vì sao giá chúng tôi luôn là số một :</h2>
					
					<p>• Khả năng đàm phán số lượng hàng lớn với các nhà cung cấp giúp chúng tôi có được giá 
					
					tốt nhất</p>
					
					<p>• Bán hàng qua mạng giúp chúng tôi tiết kiệm chi phí mặt bằng, nhân sự, vận hành…</p>
					
					<h2>Vì sao chất lượng của chúng tôi luôn là số một :</h2>
					
					<p>• Hàng hóa của chúng tôi có nguồn gốc chính hãng nên chất lượng hàng hóa được đảm 
					
					bảo 100%.</p>
					
					<p>• Hàng hóa có đầy đủ tem và được bảo hành chính hãng.</p>
					
					<p>• Chúng tôi cam kết không bán hàng kém chất lượng, không có nguồn gốc xuất xứ.</p>
					
					<h2>Vì sao dịch vụ của chúng tôi luôn là số một :</h2>
					
					<p>• Đội ngũ tư vấn bán hàng online chuyên nghiệp</p>
					
					<p>• Hàng hóa của chúng tôi được giao nhận và lắp đặt tại nhà</p>
					
					<p>• Chính sách một đổi một nếu hàng bị lỗi bởi nhà sản xuất</p>
			
			</div>
		</div>
	</div> 
</div>