<?php $this->pageClass="content-page-detail settings-page";?>
<div class="title-page">
	<div lang="en" class="wrap-content">Demo payment</div>
</div>
<div class="clearfix"></div>
<br/><br/>
<div class="wrap-content">
	<div class="col-md-12">
		<?php if(isset($this->message)) :?>
			<?php v($this->message);?>
		<?php endif;?>
		<div class="alert alert-message">
		<?php if($this->row['success'])
				  v($this->row['result']);
			   else 
			   	echo $this->row['result'];
		?>
		</div>
		<form action="/dev/pay" method="POST" class="form-horizontal">
			<div class="control-group">
				<label class="control-label" for="first_name">Amount</label>
				<div class="controls">
					<input type="Text" name="amount" value="50" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="first_name">Card Number</label>
				<div class="controls">
					<input type="Text" name="number" value="4242424242424242" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="first_name">Card Month</label>
				<div class="controls">
					<select name="year">
						<?php for($i = 1; $i <= 12; $i++) :?>
							<option value="<?php echo (0 + $i);?>"><?php echo (0 + $i);?></option>
						<?php endfor;?>
					</select>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="first_name">Card Year</label>
				<div class="controls">
					<select name="year">
						<?php for($i = 1; $i <= 10; $i++) :?>
							<option value="<?php echo (2012 + $i);?>"><?php echo (2012 + $i);?></option>
						<?php endfor;?>
					</select>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<input type="submit" name="submit" value="Submit" class="btn btn-large btn-primary"/>
				</div>
			</div>
		</form>
	</div>
</div>
