<?php $this->pageClass="content-page-detail settings-page";?>
<div class="title-page">
	<div lang="en" class="wrap-content">Demo push notification</div>
</div>
<div class="clearfix"></div>
<br/><br/>
<div class="wrap-content">
	<div class="col-md-12">
		<?php if(isset($this->message)) :?>
			<?php v($this->message);?>
		<?php endif;?>
		<form action="/dev/push-notif" method="POST" class="form-horizontal">
			<div class="control-group">
				<label class="control-label" for="first_name">Device Type:</label>
				<div class="controls">
					<select name="device_type">
						<option value="android">Android</option>
						<option value="ios">IOs</option>
					</select>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="first_name">Device ID:</label>
				<div class="controls">
					<input type="Text" name="device_id" value="" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="first_name">Trip ID:</label>
				<div class="controls">
					<input type="Text" name="id" value="" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="first_name">Trip Status:</label>
				<div class="controls">
					<input type="Text" name="status" value="" />
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<input type="submit" name="submit" value="Submit" class="btn btn-large btn-primary"/>
				</div>
			</div>
		</form>
	</div>
</div>
