<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;"><b>Contact mail</b>,</td></tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				<b>Email:</b> <?php echo $this->from;?>
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				<b>Title:</b> <?php echo $this->name;?>
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				<b>Message:</b>
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				<?php echo $this->body;?>
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
			</td>
		</tr>
	</tbody>	
</table>
