<!-- Header -->
<table cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;width:98%;">
	<tbody>
		<tr>
			<td style="font-size:12px;">
				<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:620px;">
					<tbody>
						<tr>
							<td style="font-size:16px;background:#3b5998;color:#FFFFFF;font-weight:bold;vertical-align:baseline;letter-spacing:-0.03em;text-align:left;padding:10px 38px 4px;">
								<a href="<?php echo SITE_URL;?>" target="_blank" style="text-decoration:none;" rel="nofollow">
								<span style="background:#3b5998;color:#FFFFFF;font-weight:bold;vertical-align:middle;font-size:16px;letter-spacing:-0.03em;text-align:left;vertical-align:baseline;"><?php echo DOMAIN;?></span></a>
							</td>
						</tr>
					</tbody>
				</table>
				<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;width:620px;">
					<tbody>
						<tr>
							<td style="padding:10px 20px;background-color:#fff;border-left:1px solid #ccc;border-right:1px solid #ccc;border-top:1px solid #ccc;border-bottom:1px solid #ccc;line-height:16px;">
								<table width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
									<tbody>
										<tr>
											<td style="font-size:11px;padding:10px 20px;line-height:16px;width:620px;">
<!-- /Header -->