<!-- Footer -->
											</td>
									    </tr>
									</tbody>
								</table>
							</td>
	    				</tr>
	    			</tbody>
    			</table>
				<table cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;width:620px;">
				   	<tbody>
				   		<tr>
				   			<td style="padding:10px;background-color:#fff;border-left:none;border-right:none;border-top:none;border-bottom:none;font-size:11px;color:#999999;border:none;">
				   				Email này được gửi tự động cho <?php echo $this->row['u']['mail'];?> từ website <?php echo SITE_URL;?>
				   				 
				   				Nếu bạn không muốn nhận mail như thế này, bạn có thể cài đặt trong trang web:
				   				<a href="<?php echo SITE_URL;?>" target="_blank"><?php echo ucwords(DOMAIN);?></a> 
				   				<br/>
				   				Hơibị.NÉT
				   			</td>
				   		</tr>
				   	</tbody>
				</table>
				<?php /*
				<span style="width:620px;">
					<img style="border:0;width:217px;height:80px;" src="<?php echo ASSETS_CDN?>school/img/Vieted_24.png" />
				</span>
				*/?>
			</td>
		</tr>
	</tbody>
</table>
<!-- /Footer -->