<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;">Dear <b><?php echo $this->to;?></b>,</td></tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
			Cảm ơn bạn đã sử dụng <?php echo DOMAIN?>. Để sử dụng thêm nhiều tính năng, bạn hãy kích hoat tài khoản nhé
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				Hãy kick vào link sau để kích hoạt <a href='<?php echo SITE_URL?>/user/activate?activation_code=<?php echo $this->params['activation_code']?>&id=<?php echo $this->params['id']?>&act=1'><?php echo SITE_URL?>/user/activate?activation_code=<?php echo $this->params['activation_code']?>&id=<?php echo $this->params['id']?></a>
			</td>
		</tr>
	</tbody>	
</table>
