<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;">Dear <b><?php echo $this->to;?></b>,</td></tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
			Thank you for registering on <?php echo DOMAIN;?>. To use all of our features, you need to verify your email address.
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				Please click the following link to verify <a href='<?php echo SITE_URL?>/user/verify-email?token=<?php echo $this->params['token']?>&uid=<?php echo $this->params['id']?>'><?php echo SITE_URL?>/user/verify-email?token=<?php echo $this->params['token']?>&uid=<?php echo $this->params['id']?></a>
			</td>
		</tr>
	</tbody>	
</table>
