<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;">Dear <b><?php echo $this->to;?></b>,</td></tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				At <?php echo DOMAIN;?>, we try our best to fight against spams. Our spam fighter has detected that there are some strange recent activities with your account and consequently <b>blocked</b> your account.
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				This means that you can still login and view the site's content but you cannot do anything else.
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				If you think this is an error simply reply to this email, we will address the issue appropriately. We apologize for any inconvenience caused by this.
			</td>
		</tr>
	</tbody>	
</table>
