<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;">Dear <b><?php echo $this->to;?></b>,</td></tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				Thank you for registering on <?php echo DOMAIN?>. As a member, you can:
				<br/>
				<ul>
					<li>use all of our features</li>
				</ul>
			</td>
		</tr>
		<tr>
			<td>Your <?php echo DOMAIN;?> member name is: <?php echo $this->params['name'];?></td>
		</tr>
		<tr>
			<td>We love getting feedback from members so if you ever have a comment, idea, or suggestion, please drop us a line at <?php echo CONTACT_EMAIL;?>.</td>
		</tr>
		<tr>
			<td>We're so glad you're here! </td>
		</tr>
	</tbody>	
</table>
