<div>
<b>Hướng dẫn test:</b>
<p>
-	Trước hết vào trong admin: site/admin</p>
<p>
o	Sinh ra bảng baseKarma anh nhé với link Add base karma</p>
<p>
o	Sinh ra bảng snapshot (mỗi bản ghi chỉ sinh 1 lần vậy nên làm lệnh này nhiều lần</p>
<p> 
và thay đổi giá trị tăng dần trong action add module snapshot)</p>
<p>
	Module snapshot phục vụ việc sinh ra các bảng nếu chưa có và tính toán lại các bảng anh nhé</p>
<p>
o	Cick vào link take snap shot nếu muốn tính toán lại bảng snapshot</p>
<p>
o	Click vào link rebase nếu muốn tính lại bảng base</p>
<p>
o	Click vào link top score karma để tính toán lại topuser trong 1 tuần, 1 tháng anh nhé</p>
<p>
-	Top user theo tuần, tháng và tất cả đang được hiển thị ở trong trang chủ và trang chi tiết anh nhé</p>
<p>
Đây là hướng dẫn về test anh nhé, nếu có thời gian thì anh xem có gì sai bảo em nha.</p>
</div>