<!-- Footer -->
											</td>
									    </tr>
									</tbody>
								</table>
							</td>
	    				</tr>
	    			</tbody>
    			</table>
				<table cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;width:620px;">
				   	<tbody>
				   		<tr>
				   			<td style="padding:10px;background-color:#fff;border-left:none;border-right:none;border-top:none;border-bottom:none;font-size:11px;color:#999999;border:none;">
				   				This message was sent to <?php echo $this->row['u']['mail'];?>. 
				   				If you don't want to receive these emails from 
				   				<a href="<?php echo SITE_URL;?>" target="_blank"><?php echo ucwords(DOMAIN);?></a> 
				   				<br> Vieted, Inc. Attention: Department 1111 E3B 
				   			</td>
				   		</tr>
				   	</tbody>
				</table>
				<?php /*
				<span style="width:620px;">
					<img style="border:0;width:217px;height:80px;" src="<?php echo ASSETS_CDN?>school/img/Vieted_24.png" />
				</span>
				*/?>
			</td>
		</tr>
	</tbody>
</table>
<!-- /Footer -->