<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;">Dear <b><?php echo $this->to;?></b>,</td></tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				A new password has been generated.
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				Your new password: <?php echo $this->params['password'];?>
			</td>
		</tr>
	</tbody>	
</table>
