<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;">Dear <b><?php echo $this->params['name'];?></b>,</td></tr>
		<?php if(isset($this->params['lu_id'])) :?>
			<tr>
				<td style="font-size:13px;padding:10px 0 15px 0;">
				The CEO of company "<?php echo $this->params['co']['name'];?>" has invited you to join the company on eekip.com. 
				</td>
			</tr>
			<tr>
				<td style="font-size:13px;padding:10px 0 15px 0;">
				To join or decline joining the company, please login and visit the following link 
				<a href="<?php echo SITE_URL . '/company/join?coid=' . $this->params['co']['id'] . "&uid=" . $this->params['id'];?>">
				<?php echo SITE_URL . '/company/join?coid=' . $this->params['co']['id'];?></a> 
				or follow the instructions on the website once you're logged in.
				</td>
			</tr>
		<?php else:?>
			<tr>
				<td style="font-size:13px;padding:10px 0 15px 0;">
					The CEO of company "<?php echo $this->params['co']['name'];?>" has invited you to join the company on <?php echo DOMAIN;?>.
				</td>
			</tr>
			<tr>
				<td style="font-size:13px;padding:10px 0 15px 0;">
					Since you are not yet registered with eekip.com, we have created a default password <b><?php echo $this->params['generate_password'];?></b> for you
				</td>
			</tr>
			<tr>
				<td style="font-size:13px;padding:10px 0 15px 0;">
				Please first click the following link to activate your account
				</td>
			</tr>
			<tr>
				<td style="font-size:13px;padding:10px 0 15px 0;">
					<a href="<?php echo SITE_URL . '/user/activate?activation_code=' . $this->params['activation_code'] . '&origin=invitation';?>">
					<?php echo SITE_URL . '/user/activate?activation_code=' . $this->params['activation_code'] . '&origin=invitation';?></a>
				</td>
			</tr>
			<tr>
				<td style="font-size:13px;padding:10px 0 15px 0;">
					To join or decline joining the company, visit the following link 
					<a href="<?php echo SITE_URL . '/company/join?coid=' . $this->params['co']['id'] . '&uid=' . $this->params['id'];?>">
						<?php echo SITE_URL . '/company/join?coid=' . $this->params['co']['id'];?>
					</a>  or follow the instructions on the website once you're logged in.
				</td>
			</tr>
		<?php endif;?>
	</tbody>	
</table>
