<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
	<tbody>
		<tr><td style="font-size:13px;">Dear <b><?php echo $this->to;?></b>,</td></tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
			Thank you for registering on <?php echo DOMAIN?>. To use all of our features, you need to activate your account.
			</td>
		</tr>
		<tr>
			<td style="font-size:13px;padding:10px 0 15px 0;">
				Please click the following link to activate <a href='<?php echo SITE_URL?>/user/activate?activation_code=<?php echo $this->params['activation_code']?>&id=<?php echo $this->params['id']?>&act=1'><?php echo SITE_URL?>/user/activate?activation_code=<?php echo $this->params['activation_code']?>&id=<?php echo $this->params['id']?></a>
			</td>
		</tr>
	</tbody>	
</table>
