<?php if (APPLICATION_ENV == 'development'):?>
<div data-whereami='<? echo __FILE__;?>'></div>
<?php endif;?>
<?php 
    //TO use this common comment wrapper display. Pass at least the following params to $this->
    // $this->comment_node_type
    // $this->can_comment
    // 
    
    $lu = Zend_Registry::get('user');
    $oneCommentScript = isset($this->oneCommentScript) ? $this->oneCommentScript : "widget/one-comment.phtml";
    $newCommentScript = isset($this->newCommentScript) ? $this->newCommentScript : "widget/new-comment-box.phtml";
?>
    <div id="comment_list">
        <?php if (isset($this->comments) && count($this->comments) > 0) :?>
         <?php 
         //find out relationship between user and the comments
         //such as whether or not user has voted/followed...
         $relationships = array();
         foreach ($this->comments as $i => $c)
         {
             $commentIds[] = $c['id'];
             if(isset($c['child_comments'])) {
             	foreach($c['child_comments'] as $child) {
             		$commentIds[] = $child['id'];
             	}
             }
         }
         $options = array('subject' => 'user', 'object' => 'comment_' . $this->comment_node_type);
         $relationDao = Cl_Dao_Relation::getInstance($options);
         $where = array('s.id' => $lu['id'], 'o.id' => array('$in' => $commentIds));
         $r = $relationDao->findAll(array('where' => $where));              
         if ($r['success'])
         {
             foreach ($r['result'] as $rel)
             {
                 $relationships[$rel['o']['id']] = $rel['r'];
             }
         }
         $this->relationships = $relationships;
         ?>
    	<?php foreach ($this->comments as $i => $c) :?>
    		<?php $this->c = $c;
    		    $this->zebraClass = ($i % 2 == 1)? 'altodd' : 'alteven';  
    		    $this->commentEditable = false;
    		    if ($c['u']['id'] == $lu['id'] || has_perm('admin_comment'))
    		        $this->commentEditable = true;
    		?>
    		<?php echo $this->render($oneCommentScript);?>
    	<?php endforeach;?>
    	<?php endif;?>
    </div>
    
    <?php //==================NEW COMMENT BOX ======================== ?>
    <div class='altodd comment' id='new_comment' style='display:block;'>
    	<a name="new_comment"></a>
    	<hr/>
		
		<?php if($this->can_comment){?>
			<?php echo $this->render($newCommentScript);?>
		<?php }else{?>
    		<div id='login-to-comment'>
    	    You must <a href="/user/login">log in</a> to comment
    	    </div>
		<?php }?>
	</div>