<?php if (APPLICATION_ENV == 'development'):?>
<div data-whereami='<? echo __FILE__;?>'></div>
<?php endif;?>

<?php $pageType = Zend_Registry::get('page_type');?>
<?php $filter = $this->filter;?>
<?php /* Get current url */ ?>
<?php 
	if(isset($_SERVER["REQUEST_URI"]) && $_SERVER["REQUEST_URI"] != '/' && checkLink($_SERVER["REQUEST_URI"])){
		$link = $_SERVER["REQUEST_URI"];
	}else{
		$link = "/hot";
	}
	if(!isset($this->storyTypeInt)) 
        $storyTypeInt == '';
	else 
	    $storyTypeInt = $this->storyTypeInt; 
?>
<div class="ct-post">
<p class="ct-tags">
	<a <?php if($storyTypeInt == '') echo "class='active'"?> 
	    style = "margin-right: 5px;" href="<?php echo SITE_URL.'/'.$filter;?>"><?php echo t('all',1);?></a>

	<a <?php if($storyTypeInt == 2) echo "class='active'"?> 
	    style = "margin-right: 5px;" href="<?php echo SITE_URL.'/'.nav_link($filter,'2');?>"><?php echo t('fun_picture',1);?></a>
	<a <?php if($storyTypeInt == 1) echo "class='active'"?> 
	    style = "margin-right: 5px;" href="<?php echo SITE_URL.'/'.nav_link($filter,'1');?>"><?php echo t('fun_story',1);?></a>
	<a <?php if($storyTypeInt == 3) echo "class='active'"?> 
	    style = "margin-right: 5px;" href="<?php echo SITE_URL.'/'.nav_link($filter,'3');?>"><?php echo t('fun_video',1);?></a>
	<a <?php if($storyTypeInt == 4) echo "class='active'"?> 
	    style = "margin-right: 5px;" href="<?php echo SITE_URL.'/'.nav_link($filter,'4');?>"><?php echo t('fun_quiz',1);?></a>
<?php
/* 
	<a <?php if($storyTypeInt == 6) echo "class='active'"?> 
	    style = "margin-right: 5px;" href="<?php echo $link?>/link-vui"><?php echo t('fun_link',1);?></a>
	<a <?php if($storyTypeInt == 5) echo "class='active'"?> 
	    style = "margin-right: 5px;" href="<?php echo $link?>/flash-game"><?php echo t('flash_game',1);?></a>
*/	    
?>
</p>
</div>

<?php if ($pageType == 'story'):?>
<?php elseif ($pageType == 'story-category'):?>
<?php elseif ($pageType == 'user'):?>
<?php elseif ($pageType == 'tag'):?>
<?php endif;?>


<?php /*checking currentlink - if equal then change it*/?>
<?php 
	 function checkLink($currentLink){
		$linkArray = array('/hot','/new','/best','/vote');	
		foreach ($linkArray as  $row){
			if(strcmp($currentLink,$row) == 0)
				return  TRUE;
		}
		
		return  FALSE;
	}

?>