<?php 
$page = Zend_Registry::get('page_nr');
$filter = $this->filter;
?>
<?php 
    $minPoint = 7;
    $maxPoint = 10;  
?>
<?php if (APPLICATION_ENV == 'development'):?>
<div data-whereami='<? echo __FILE__;?>'></div>
<?php endif;?>

<?php 
    $isWidget = (isset($this->is_widget) && $this->is_widget == 'widget') ? true:false;
?>
<?php if (!$isWidget):?>
<div id='story-filter'>
	<?php echo $this->render('widget/story-list-filter.phtml');?>
</div>

<?php endif;?>

<?php if(isset($this->slug)){?>
	<div id ="detail-tag-special" data-url='/widgettag/<?php echo $this->slug?>' class='sand-ajax-widget'>
    	</div>
<?php }?>

<?php if (!$isWidget):?>

<div id="story-list">
<?php if($filter == "vote"):?>
	<!-- Note for Vote -->
	<div class="alert alert-success alert-dismissable">	
	
	<?php  echo t(note_for_vote1) ;?>
	<br>
	<?php  echo t(note_for_vote2_1) ;?><i class="vote-up-btn glyphicon glyphicon-circle-arrow-up"></i>
	<?php  echo t(note_for_vote2_2) ;?><i class="vote-down-btn glyphicon glyphicon-circle-arrow-down"></i><?php  echo t(note_for_vote2_3) ;?>
	<br>
	<b><?php  echo t(note_for_vote3) ;?></b>
	</div>
<?php endif;?>
<?php endif;?>

<?php if (isset($this->list) && count($this->list) > 0):?>
    <?php $j = 0; $n = 2; //number of image that's load without lazy?>
    <?php  foreach($this->list as $c => $row):?>
<div>
<?php //if story is not approved (voting) and point >=7 and <= 10 . its will be go to new page?>
    <?php if($row['status'] == 'queued'):?>
        <?php if($row['counter']['point'] >= $minPoint && $row['counter']['point'] < $maxPoint): ?>
             <div class="alert alert-success alert-dismissable">
                 <?php echo sprintf(t("this_story_need_%1.2f_more_points_to_go_to_new_page_please_vote_for_this"),
                         $maxPoint-$row['counter']['point']);
                 ?>
             </div>
        <?php endif;?>
    <?php endif;?>
    <?php if(has_perm('sudo') || has_perm('admin_story')):?>
    <?php //help admin manage all stories?>
         <div class="alert alert-success alert-dismissable">
             <span class='bold' style='color:red;'>Root-only statistics</span> <br/>
             Points: <?php echo $row['counter']['point']; ?></br>
             Hotness: <?php echo $row['counter']['hn']; ?></br>
             Status: <?php echo $row['status']; ?></br>
             Uiid: <?php echo $row['u']['iid']; ?> ||
             Uname: <?php echo $row['u']['name']; ?> ||
             Ulname: <?php echo $row['u']['lname']; ?>
         </div>
    <?php endif;?>
</div>
    <?php $j++; ?>
		<?php $storyType = story_type($row['type']);
			if (!isset($row['counter']['vd']))
				$row['counter']['vd'] = 0;
			if (!isset($row['counter']['vote']))
				$row['counter']['vote'] = 0;
			if (!isset($row['counter']['c']))
				$row['counter']['c'] = 0;
				
		?>
		<!-- show ra 1 dong-->
		<?php if($filter != "hot" && $filter != "best"):?>
		<div class='row' style='padding-top:0px;margin-top:0px;'>
    		<div class='col-md-12' style='padding-top:0px;margin-top:0px;'>
    		    <div class="page-header" style='padding-top:15px;margin-top:0px;padding-bottom:0px;margin-bottom:0px;border-bottom:none;'>
                      <h3 style='padding-top:0px;margin-top:0px;'>
                          <a style="text-decoration: none" target='_blank' data-href="<?php echo node_link('story',$row)."#view";?>"
                            href="<?php echo node_link('story',$row)."#view";?>" title="<?php echo t("click_here_to_view",1);?> <?php echo $row['name'];?>">
        					<!-- <i class='<?php echo story_icon($storyType);?>'></i> -->
        					<?php echo $row['name'];?>
        				</a>
        				<br/>
        				 <small>
        				     <a href='<?php echo user_link($row['u']);?>' class="user-link"><?php echo $row['u']['name'];?></a>,
        				    <span class="timeago" title="<?php echo convert_ts_to_js($row['ts']);?>"></span>
        				</small>
    				</h3>
                </div>
    		</div>
		</div>
		<?php endif;?>
		<div class="row story-wrapper stickem-container" id="<?php echo $row["iid"] ?>" style='padding-top:0px;margin-top:0px;'>
		    
			<div class="col-md-9" >
			<?php 
			if(isset($row['type'])){
				if($storyType == 'image' || $storyType == 'video'){
					if ($storyType == 'image')
						$imgLink = story_image($row);
					else 
						$imgLink = "http://img.youtube.com/vi/{$row['ytid']}/0.jpg";
					
						
					$node_link=node_link('story',$row);
					$link = SITE_URL;
					if ($storyType == 'image')
					{
						if(!$row['is_iphone'])
						{
						    for ($i=0;$i<count($imgLink);$i++){
						        $file_header = @get_headers($imgLink[$i]);
								if($file_header[0] == 'HTTP/1.1 404 Not Found'){
								    $imgLink[$i] = str_replace("1000/","",$imgLink[$i]);
								}
								if (!$isWidget): ?>
	    							<a href="<?php echo $node_link?>#view" 
	    							   data-href="<?php echo $node_link?>#view"
	    							   target='_blank' title=" <?php echo t("click_here_to_view",1). ' ' .$row['name'];?>">
	    								<img  style="width: 482px;" class="<?php if($j>$n):?> lazy <?php endif;?> 
	    								img-polaroid img-responsive" 
	    								src="<?php if($j>$n): echo $link;?>/image_editor/icon/grey.gif 
	    								     <?php else: echo $imgLink[$i]; endif;?>"
	    								data-original="<?php echo $imgLink[$i];?>">
	    							</a>
	    							<br/>
								<?php else:?>
    							<a href="<?php echo $node_link?>#view"
    							   data-href="<?php echo $node_link?>#view" 
    							   target='_blank' title="<?php echo t("click_here_to_view",1). ' ' .$row['name'];?>">
    								<img style="width: 482px;" class="lazy img-polaroid img-responsive" src="<?php echo $imgLink[$i];?>">
    							</a>
    							<br/>
								<?php endif;?>
						<?php 
							}
							
						}
						else 
						{
    						$file_header = @get_headers($imgLink[$i]);
							if($file_header[0] == 'HTTP/1.1 404 Not Found'){
    								    $imgLink[0] = str_replace("1000/","",$imgLink[0]);
    								}
    						if(!$isWidget): ?>
								<a href="<?php echo $node_link?>#view" 
								    data-href="<?php echo $node_link?>#view"
								    target='_blank' title="<?php echo t("click_here_to_view",1). ' ' . $row['name'];?>">
									<img style="min-height: 482px;" class="iphone lazy img-polaroid img-responsive" src="<?php echo $link;?>/image_editor/icon/grey.gif" data-original="<?php echo $imgLink[0];?>">
								</a>
								<br/>
    						<?php else:?>
								<a href="<?php echo $node_link;?>#view"
								   data-href="<?php echo $node_link;?>#view"
								   target='_blank' title="<?php echo t("click_here_to_view",1). ' ' .$row['name'];?>">
									<img style="min-height: 482px;" class="lazy img-polaroid img-responsive" src="<?php echo $imgLink[0];?>">
								</a>
								<br/>
    						<?php endif;?>
    						<?php 
							
						}
					
					}
					else
					{
						$videoPlayImage = SAND_ASSETS_CDN . '/images/video-play-button.png';
						if(!$isWidget): ?>
							<a href="<?php echo $node_link;?>#view"
							   data-href="<?php echo $node_link;?>#view" 
							   target='_blank' title="<?php echo t("click_here_to_view",1). ' ' .$row['name'];?>">
								<img class="lazy img-polaroid img-responsive" src="<?php echo $link;?>/image_editor/icon/grey.gif" data-original="<?php echo $imgLink;?>">
		 						<img src="<?php echo $videoPlayImage;?>" class="videoIndicator"/>
							</a>
							<br/>
						<?php else:?>
							<a href="<?php echo $node_link;?>#view"
							   data-href="<?php echo $node_link;?>#view" 
							   target='_blank' title="<?php echo t("click_here_to_view",1). ' ' .$row['name'];?>">
								<img class ="lazy img-polaroid img-responsive" src="<?php echo $imgLink?>">
		 						<img src="<?php echo $videoPlayImage;?>" class="videoIndicator"/>
							</a>
							<br/>
						<?php endif;?>
						<?php
					} 
				}
			}
			?>
			<?php 	
            if(isset($row['type'])){
               if($row['type'] == 2 || $row['type'] == 3 )
				{
					//Nothing...
				}else{
					echo $row['content'];
				}
			}else{
				if ($storyType != 'quote')
					echo $row['content'];
			}
			
			?>
			<?php if ($storyType == 'quote'):?>
			<blockquote>
		    	<p><a href='<?php echo node_link('story', $row);?>'><?php echo $row['name'];?></a></p>
		    	<small><?php if (isset($row['by']) && $row['by'] != ''):?><?php echo $row['by'];?><?php else:?><?php echo t('guest',1);?><?php endif;?></small>
		    </blockquote>
			<?php endif;?>
			<?php if ($storyType == 'multi-choice'):?>
			
			     <div class="row" id="collapse" data-votes = "<?php echo $vote;?>" data-vd = "<?php echo $vd;?>" data-spam="<?php echo $spam;?>">
                    <a title="<?php echo t("pair_two_choose",1);?>" 
                    	data-iid = <?php echo $row['iid']."-vote-up";?>
                         id = <?php echo $row['iid']."-vote-up";?>
                    	class=" cl_ajax has-tooltip pair_one_choose cl_login btn btn-lg btn-danger col-md-6" 
                        _cl_get_metadata="choose_pair_one_success vote_success" 
                        href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=5">
                        <?php echo $row['pair1'];?>
                      </a>
                      <span class='light-black vote_up' id="vote_up_count" style="display:none;"><?php echo $vote;?></span>
                      
                      <a title="<?php echo t("pair_two_choose",1);?>" 
                      	 data-iid = <?php echo $row['iid']."-vote-down";?>
                         id = <?php echo $row['iid']."-vote-down";?>
                      	 class="cl_ajax has-tooltip pair_two_choose cl_login  btn btn-lg btn-danger col-md-6"
                      	_cl_get_metadata="choose_pair_one_success vote_success" 
                      	href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=6">
                      	<?php echo $row['pair2'];?>
                      </a>
                      <span class='light-black vote_down'  id="vote_down_count" style="display:none;">              
                      <?php echo $vd?>
                      </span>
                </div>
                <br/>
			    <?php $imgLink = story_image($row);
        			    for ($i=0;$i<count($imgLink);$i++){
        			        $file_header = @get_headers($imgLink[$i]);
        			        if($file_header[0] == 'HTTP/1.1 404 Not Found'){
        			            $imgLink[$i] = str_replace("1000/","",$imgLink[$i]);
        			        }
						if (!$isWidget): ?>
							<a href="<?php echo $node_link?>#view" 
							   data-href="<?php echo $node_link?>#view"
							   target='_blank' title=" <?php echo t("click_here_to_view",1). ' ' .$row['name'];?>">
								<img  style="width: 482px;" class="<?php if($j>$n):?> lazy <?php endif;?> 
								img-polaroid img-responsive" 
								src="<?php if($j>$n): echo $link;?>/image_editor/icon/grey.gif 
								     <?php else: echo $imgLink[$i]; endif;?>"
								data-original="<?php echo $imgLink[$i];?>">
							</a>
							<br/>
						<?php else:?>
						<a href="<?php echo $node_link?>#view"
						   data-href="<?php echo $node_link?>#view" 
						   target='_blank' title="<?php echo t("click_here_to_view",1). ' ' .$row['name'];?>">
							<img style="width: 482px;" class="lazy img-polaroid img-responsive" src="<?php echo $imgLink[$i];?>">
						</a>
						<br/>
    						<?php endif;?>
    				<?php 
    					}
			    
			    
			    ?>
			<?php endif;?>
			
			</div> <!-- end span9 -->
			<div class="col-md-3 stickem">
			<?php if($filter != "hot" && $filter != "best"):?>
				<!-- Vote box after title -->
			    <!--<div class='well light-black-bg'>-->
                                <ul class="nav   horizontal-vote " > 
                                    <li data-vote = "<?php echo $row['counter']['vote'];?>">
                                        
                                        <?php if(!isset($row['isVoteUp']) ):?>
                                    <a class="badge-item-vote-up up cl_ajax has-tooltip vote-up cl_login" title="<?php echo t('vote_up',1);?>" 
                                    	data-iid = <?php echo $row['iid']."-vote-up";?>
                                    	id = <?php echo $row['iid']."-vote-up";?>
                                    	     	 _cl_get_metadata="vote_story_success vote_success" 
                                    	 href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=1&type=<?php echo $this->filter;?>">
                                        
                                    </a>
                                        
                                 <?php endif; ?> 
                                        
                                    </li> 
                                    <li>
                                        <?php if(!isset($row['isVoteDown'])):?>
                                  <a title="<?php echo t('vote_down',1);?>" 
                                  id = <?php echo $row['iid']."-vote-down";?>
                                  data-iid = <?php echo $row['iid']."-vote-down";?>
                                  class="badge-item-vote-up down cl_ajax has-tooltip hide_me cl_login" votes="<?php echo $row['counter']['vd'];?>"
                                   _cl_get_metadata="unvote_story_success unvote_success" href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=4&type=<?php echo $this->filter;?>">
                                  </a>
                                   <?php endif;?>
                                    </li> 
                                </ul>
                                <div style="display:table">
                            <ul class="others" id="count-vote-comment" >
                                <li>
                                    <a  class="voteCounter" href="<?php echo node_link('story',$row)."#view";?>">
                                      <div class='col-md-6 text-right' style="width:50%;float:left;" title = <?php echo t("total_of_voteup_and_votedown",1);?>>
	    								<i class='<?php echo get_icon('heart');?>'></i>
	    								<?php $totalVotes = $row['counter']['vote'] + $row['counter']['vd'];?>
	    								<span class="totalVotes" id="<?php echo "total-vote-".$row['iid']?>" ><?php echo $totalVotes;?></span>
	    								
				    					</div>
				    					<div class='col-md-6 text-left' style="width:50%;float:left;">
			    					            <i class="<?php echo get_icon('comment');?>"></i>
			        							<span>
			            							<?php 
			            								if(isset($row['counter']['c'])) 
			            								    echo $row['counter']['c'];
			            								else 
			            								    echo "0";
			                              			?>
			                          			</span>
			        					
				    					</div>
	                                    </a>
                                	</li>
                                </ul>
                           <ul class="others" id="id-other-fblike">
                                <li>
                                    <a class="fblike">
                                    <div class="fb-like" data-send="false"
                                             contenteditable=""accesskey=""data-href="<?echo SITE_URL;?><?php echo node_link('story',$row);?>" 
                                             contextmenu=""data-layout="button_count" data-width="90" 
                                             data-bind=""data-show-faces="false">
                                    </div>
                                    </a>
                                </li>
                             </ul>
                             <ul class="others">
                                <li >
                                    <?php if(!isset($row['isVoteDown'])):?>                                     
                                          <a title="<?php echo t('mark_spam',1);?>" 
                                          id = <?php echo $row['iid']."-mark-spam";?>
                                          data-iid = <?php echo $row['iid']."-mark-spam";?>
                                          class=" cl_ajax has-tooltip mark-spam hide_me cl_login" 
                                          votes="<?php echo $row['counter']['spam'];?>"
                                           _cl_get_metadata="mark_spam_success" href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=3&type=<?php echo $this->filter;?>">
                                            <i  class="mark-spam-btn <?php echo get_icon('remove');?>" ></i>                                            
                                            <?php echo t('mark_spam',1) ?>
                                            </a>
                                           <?php endif;?>
                                </li>
                                
                            </ul>   
                            </div>      
                             <?php if (isset($row['tags']) && count($row['tags']) > 0) :?>
                            <ul>
                                <li>
                                    <?php foreach ($row['tags'] as $tag) :?>
    						<?php echo display_tag($tag);?>
    					<?php endforeach;?>
                                </li>
                            </ul>
                            <?php endif;?>
                           
				<?php else:?>
    					 <div class="page-header" style="margin-top: 20px;">
	                      <h2 class="story-title">
	                          <a style="text-decoration: none;" target='_blank' data-href="<?php echo node_link('story',$row)."#view";?>"
	                            href="<?php echo node_link('story',$row)."#view";?>" title="<?php echo t("click_here_to_view",1);?> <?php echo $row['name'];?>">
	        					<!-- <i class='<?php echo story_icon($storyType);?>'></i> -->
	        					<?php echo $row['name'];?>
	        				</a>
	    				</h2>
        				 <small>
        				    <a href='<?php echo user_link($row['u']);?>' class="user-link"><?php echo $row['u']['name'];?></a>,
        				    <span class="timeago" title="<?php echo convert_ts_to_js($row['ts']);?>"></span>
        				</small>
	                    </div>
	                    <div class="text-left">
	    					<span class="fb-like" 
	    					alt="<?php echo $row['name'];?>"
	    					data-href="<?php echo SITE_URL;?><?php echo node_link('story',$row);?>" 
	    					data-colorscheme="light" 
	    					data-layout="button_count" 
	    					data-action="like" 
	    					data-show-faces="false" 
	    					data-send="false">
	    					</span>
	    					<br>
	                    	<span>
    					            <i class="<?php echo get_icon('comment');?>"></i>
        							<span>
            							<?php 
            								if(isset($row['counter']['c'])) 
            								    echo $row['counter']['c'];
            								else 
            								    echo "0";
                              			?>
                          			</span>
    						</span>
    						<span>
    					            <i class="<?php echo get_icon('eye-open');?>"></i>
        							<span>
            							<?php 
            								if(isset($row['counter']['v'])) 
            								    echo $row['counter']['v'];
            								else 
            								    echo "0";
                              			?>
                          			</span>
    						</span>
    					</div>
				<?php endif;?>
			</div>
		</div>
		
		<!-- End show ra 1 dong -->
		<?php endforeach;?>
		<!-- End for show ra 1 dong -->
		
<?php else:?>
	<div class='alert alert-error'><i class='<?php echo get_icon('warning-sign', $type = 'glyph');?>'> Error: <?php echo t('nothing_found');?></i></div>
	<div style='text-align:center;'>
		<img src='<?php echo not_found();?>' />
	</div>
<?php endif;?>	


<?php 
		$page = Zend_Registry::get('page_nr');
		 $base = Zend_Registry::get('base_url');
		 $total = Zend_Registry::isRegistered('total') ? Zend_Registry::get('total') : isset($this->total) ? $this->total : 1;
		 $prevUrl = ($page > 1) ? $base . ($page - 1) : "#";
		 $nextUrl = ($page == $total) ? "#" : $base . ($page + 1); 
    ?>
    <!-- pagination -->
    <div class='separator-high'></div>
    <div class='row' style='font-weight:bold;' id= "nav-footer">
    	<div class='col-md-12'>
    		<a id='next-page' title='<?php echo t('click_here_to_get_more_fun',1);?>' 
    		    href='<?php echo $nextUrl?>'
    		    data-href-widget="<?php echo $nextUrl?>/widget" 
    		    class='btn btn-block btn-primary btn-large <?php if ($page == $total):?>disabled<?php Endif;?>'><?php echo t('load_more_fun',1);?><i class="icon-forward"></i></a>
    	</div>
    </div>
    
    <?php if (!$isWidget):?>
        <div class='row' style='font-weight:bold;display:none;' id="loading">
        	<div class='col-md-12'>
        		<button class='btn btn-block btn-primary btn-large'><?php echo t('loading',1);?> ...</button>
        	</div>
    	</div>
    <?php endif;?>
    
<?php if (!$isWidget):?>	
</div> <!-- End div story-list -->
<?php endif;?>

