<?php $page = Zend_Registry::get('page');?>
<ul class='nav nav-pills'>
	<li <?php if ($page == 'contact/index/new') echo "class='active';"?>>
		<a href="/contact/new">Tạo mới</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'contact/index/update') echo "class='active';"?>>
		<a href="/contact/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>"">
		Cập nhật</a></li>
	<?php endif;?>    
	<li <?php if ($page == 'contact/index/search') echo "class='active';"?>>
		<a href="/contact/search">Tìm kiếm</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'contact/index/view') echo "class='active';"?>>
		<a href="/contact/<?php if (isset($this->row['id'])) echo "" . $this->row['id'];?>">Xem chi tiết</a></li>
	<?php endif;?>
</ul>
<div class='separator'></div>
