<div class="row">
<?php 
	$form = new User_Form_Register();
	$form->build();
	$form->setAction('/user/register')
	->setAttrib('class', 'cl_ajax');
?>
  <section class="nine columns signup-section">
    <div class="module">
      <h1 class="section-title">
        Sign Up
        <span>
          or
          <a href="<?php echo SITE_URL?>/user/login">
            Sign In
          </a>
        </span>
      </h1>

      <div class="module-body">
        <div class="row" id="signup">
            <div data-bhw="SignUp" class="facebook-login five columns" data-bhw-path="SignUp">
              <h3>
                Sign up with your Facebook account
              </h3>
          
              <p>Connect your Facebook account to sign up to Groupon.</p>
          
              <div class="fb-login-button">
                <div class="facebook-login-button"></div>
              </div>
            </div>
          <div class="section-spacer">
            <span>or</span>
          </div>
          
          <div class="groupon-signup six columns push-one">
            <h3>
            <h3>Đăng ky với tài khoản <?php echo SITE_NAME;?></h3>
            </h3>
            <?php echo $form;?>
          </div>
          
        </div>
      </div>
    </div>
  </section>

  <section class="three columns">
    <section data-bhw="GrouponPromise" id="promise" class="module" data-bhw-path="GrouponPromise">
      <h3 class="module-title">Our Promise To You</h3>
  
      <div class="module-body">
        <p>We're confident in the businesses we feature on Groupon and back them with the Groupon Promise.</p>
        <p>
          <a href="/groupon-promise">Learn more</a>
        </p>
      </div>
    </section>
  </section>
</div>