<?php $page = Zend_Registry::get('page');?>
<b><a href='/site/admin'>Admin >></a></b>
<ul class='nav nav-tabs'>
	<li <?php if ($page == 'story/index/new') echo "class='active';"?>><a href="/story/new">New</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'story/index/update') echo "class='active';"?>><a href="/story/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>"">Update</a></li>
	<?php endif;?>    
	<li <?php if ($page == 'story/index/search') echo "class='active';"?>><a href="/story/search">Search</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'story/index/view') echo "class='active';"?>><a href="<?php echo node_link('story', $this->row);?>">View</a></li>
	<?php endif;?>
</ul>