<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='row'>
	<?php 
	    if (get_value('iphone')):?>
	    <?php 
	        $text = t('create_iphone_chat', 1);
	    ?>
        <div class='col-md-12'>
    	<h3> <?php echo $text;?> </h3>
        </div>
    <?php endif;?>    
    <?php if (get_value('iphone', '') == ''):?>
	<div class='col-md-12'>
	<?php  echo $this->render('index/storytype-nav.phtml');?>
	</div>
	<?php endif;?>
	
	<div class='col-md-6'>
	
	<?php $this->form->setAttrib('class', 'cl_ajax form-inline');
	$this->form->setAttrib('id', 'new-story')
	?>
	
	<?php 
	echo $this->form;?>
	</div>
	
	<div class='col-md-6'>
<?php //iphone chat help?>	
<?php if (get_value('iphone', '') != ''):?>
<h3><?php echo t('help', 1);?></h3>
	    <div class='alert alert-info'>
	    <?php echo get_conf('iphone_help', 'iphone_help in conf');?>
	    </div>
	    <?php echo t('sample_iphone_chat',1);?>
<div class='well'>
<?php echo get_conf('sample_iphone_chat', 'sample_iphone_chat in conf');?>
</div>
<?php endif;?>    	
	<a href="#" id="preview_post_btn" class='btn btn-primary' data-form-target-id='new-story'><?php echo t('preview',1);?></a>
	    <div id='preview_area'>
	    	<div class="images"></div>
            <?php /*<canvas id="canvas" style="position:relative;"></canvas>*/?>
	    </div>
	</div>
</div>

<?php $this->headScript()->appendFile(ASSETS_CDN . "/js/post.js",'text/javascript'); ?>
