<div class='row'>
<div class='col-md-12'>
<?php echo $this->render('index/navbar.phtml');?>
</div>

<div class='separator-high'></div>

<div class='col-md-2'>
    <div class='search_form well well_shallow'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-10'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/story/bulk-delete" class="cl_ajax btn btn-danger btn-xs" id='bulk-delete'><?php echo t('delete_selected',1);?></a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<th>ID</th>
        			<th style="width: 120px;">Thumb</th>
        			<th>Name</th>
        			<th>Type</th>
        			<th>Stats</th>
        			<th>Status</th>
        			<th>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<?php $row['counter'] = array_merge(array('c' => 0, 'v' => 0, 'point' => 0,
        		        'vd' => 0, 'vote' => 0, 'hn' => 0
        		    ), $row['counter']);?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<td><?php echo $row['iid'];?></td>
        			<td>
                            <a href="<?php echo node_link('story', $row);?>">
                    		<?php if(isset($row['type'])):
                    	               $storyType = story_type($row['type']);?>
                    	                   
                    	 	     <?php if($storyType == 'image'):?>
                                        <?php 
                    	                    //$image =  STATIC_CDN . '/170/' . $row['url'];
                    	                    $image =  PUBLIC_FILES_UPLOAD_PATH . '/170/' . $row['url'];
                    	                    $checkImage =  @getimagesize($image);
                                        ?>
                                    <img  style="width:100px;" src="<?php
                                            if(is_array($checkImage))
                                            {
                                                echo STATIC_CDN . '/170/' . $row['url'];
                                                $url = STATIC_CDN . '/170/' . $row['url'];
                                            }
                                            else
                                            {
                                                echo STATIC_CDN . $row['url'];   
                                                $url = STATIC_CDN . $row['url'];
                                            }
                                    ?>"
                                    >
                                <?php endif;?>
    		                  </a>
                <?php endif;?>
                    
                <?php if($storyType == 'video'):?>
                	<?php 
                		$imgLink = "http://img.youtube.com/vi/{$row['ytid']}/0.jpg";
                	?>
                		<img style="width:100px;"  src="<?php echo $imgLink;?>">
                <?php endif;?>
        			</td>
        			<td>
            			<a target='_blank' href="<?php echo node_link('story', $row);?>"><?php echo $row['name'];?>
            			</a>
        	
            			<br/><span class='timeago' title="<?php echo convert_ts_to_js($row['ts']);?>"></span>
            			<Br/>
            			  <?php echo t('by',1);?>  <a href="<?php echo user_link($row['u']);?>" class="user-link">
                  <?php echo char_breadcumb($row['u']['name'], 20);?></a>
                  
        			</td>
        			<td><?php echo story_type($row['type']);?></td>
        			<td>
        			View: <?php echo $row['counter']['v'];?><br/>
        			Comment: <?php echo $row['counter']['c'];?><br/>
        			HN: <?php echo $row['counter']['hn'];?><br/>
        			Point: <?php echo $row['counter']['point'];?><br/>
        			Vote: <?php echo $row['counter']['vote'];?><br/>
        			Vote down: <?php echo $row['counter']['vd'];?><br/>
        			
        			</td>
        			<td>
        			    <div class="btn-group">
        			    	<a title='Queued' href="/story/update?id=<?php echo $row['id'];?>&status=queued&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='queued') echo 'active';?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group"> Q </a>
        			    	<a title='Approved' href="/story/update?id=<?php echo $row['id'];?>&status=scheduled&_cl_step=status" 
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='scheduled') echo 'active';?> cl_ajax" _cl_get_metadata="active_button_group"> Sched</a>
        			    	<a title='Spammed' href="/story/update?id=<?php echo $row['id'];?>&status=spammed&_cl_step=status" 
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='spammed') echo 'active';?> cl_ajax" _cl_get_metadata="active_button_group"> Spam</a>
        			    	<a title='Approved' href="/story/update?id=<?php echo $row['id'];?>&status=approved&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='approved') echo 'active';?> cl_ajax" _cl_get_metadata="active_button_group"> Apved</a>
        			    	<?php $isFeatured = Dao_Node_Story::getInstance()->isFeatured($row);?>
        			    	
        			    	<a title='feature' href="/story/update?id=<?php echo $row['id'];?>&is_feature=1&_cl_step=feature"
        			    	 class="btn btn-warning btn-xs  cl_ajax " _cl_get_metadata="active_button_group hide_me_show_next"
        			    	 <?php if($isFeatured) echo 'style="display:none"';?>
        			    	 >
        			    	  Feat.
        			    	</a>
        			    	<a title='Unfeature' href="/story/update?id=<?php echo $row['id'];?>&is_feature=0&_cl_step=feature"
        			    	 class="btn btn-xs  cl_ajax " _cl_get_metadata="active_button_group hide_me_show_prev"
        			    	 <?php if(! $isFeatured) echo 'style="display:none"';?>
        			    	 >
        			    	  Unfeat.
        			    	</a>
        			    </div>     
        			</td>
        			
        			<td>
        				<a href="/story/update?id=<?php echo $row['id']?>" class="btn btn-xs btn-default"><i class="icon-edit"></i>Edit</a>
        				<?php if($storyType == 'image'):?>
        				<a href="/site/rage-maker?id=<?php echo $row['id']?>&edit=true" class="btn btn-xs btn-default"><i class="icon-edit"></i>Edit Images</a>
        				<?php endif;?>
        				<a href="/story/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" _cl_get_metadata="remove_my_parent:2">
        					<i class="icon-remove"></i>Delete
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No story found</h3>
    <?php endif;?>
</div>

</div>