<div class='row'>
<?php if (isset($this->row)) :?>
<div class='col-md-12'>
    <?php echo $this->render('index/navbar.phtml');?>
</div>

	<div class="col-md-6" style="margin-left:0">
    	<h3> Update Story </h3>
    	<a href='/story/delete?id=<?echo $this->row['id'];?>' class='cl_ajax' _cl_get_metadata='alert_success'>Delete</a> 
        <?php $this->form->setAttrib('class', 'cl_ajax');?>
        <?php 
        if (isset($this->successMsg)) 
            echo "<div class='alert alert-success'>" . $this->successMsg . "</div>";
            
        if (isset($this->err) && $this->err != null && $this->err != '')
        { 
            echo "<div class='alert alert-error'>";
            if (is_string($this->err)) 
                echo $this->err; 
            elseif (is_array($this->err)  && count($this->err) > 0)
            {
                echo "<ul>";
                foreach ($this->err as $e)
                    echo "<li>$e</li>";
                echo "</ul>";
            }
            echo "</div>";
        }
        ?>
  
        <?php 
        	echo $this->form;
        ?>
	</div>
    <div class='col-md-6'>
    <div class='separator'></div>
	<a href="#" id="preview_post_btn" class='btn btn-primary'><?php echo t('preview',1);?></a>
	    <hr/>
	    <div id='preview_area'>
            <div class="images"></div>
            <canvas id="canvas" style="position:relative;"></canvas>
        </div>
	</div>

<?php $this->inlineScript()->captureStart();?>
$(function(){
    $('#upload_img, #upload_img-label, #upload_img-element').show();
    <?php if($this->row['type'] == 4) :?>
        $('#url, #url-label').show();
        $('#upload_img-label, #upload_img-element').hide();
    <?php endif;?>
    <?php if(isset($this->row['images'])) :?>
    var fileList = JSON.parse($("#images").val());
    var str = "";
    var $ul = "<ul class='nav nav-list'>";
    $.each(fileList, function(i, val){
        img = "/ufiles/<?php echo IMG_CONCATE_SIZE;?>/" + val.id + "." + val.ext;
        str += "<div class='col-md-1' style='position:relative;margin:10px;'><a href='javascript:;' id='" +val.id+ "' class='remove_img dom_remove' style='position:absolute;top:-10px;right:-10px;'><i class='<?php echo get_icon('remove');?>'></i></a><img src='" + img + "' class='thumbnail' style='width:60px;height:60px;'/></div>";
        $ul += "<li id='" +val.id+ "' style='position:relative;'><img src='" + img + "'/></li>";
    });
    str += "<div class='clearfix'></div>";
    $ul += "</ul>";
    $("#upload_img").closest('form').find("#upload_img-label").html(str);
    $(".images").html($ul);
    /*
    $("#preview_area .images ul").sortable({
    	update: function (e, ui) {
			genCanvas();
		}
    });
    */
    <?php endif;?>
});
<?php $this->inlineScript()->captureEnd();?>
<?php else:?>
       <div class='col-md-12'>
       <div class='alert alert-warning'><?php echo t('object_not_found',1);?></div>
       </div>
<?php endif;?>
<?php $this->headScript()->appendFile(ASSETS_CDN . "/js/post.js",'text/javascript'); ?>
</div>