<?php echo sand_dev_info_phtml(__FILE__);?>

<?php 
    $isPreview = is_preview();
	$lu = Zend_Registry::get('user');
	$row = $this->row;
	$rowN = $this->rowN; //next story
	$rowP = $this->rowP; //previous story
	f($row);
	$storyType = story_type($row['type']);

	/*
	if ($storyType == 'image')
	{
		if(strpos($row['url'] , "http://") === 0 || strpos($row['url'] , "https://") === 0){
			Zend_Registry::set('ogImage',$row['url']);	
		}else{
			Zend_Registry::set('ogImage', STATIC_CDN . '/370/'.  $row['url']);
		}	
	}
	*/
	$isModal = is_modal_ajax();
?>
<script>
CL.nid = '<?php echo $row['id']?>';
</script>

<?php if (!$isModal):?>
    <div class="row index-list">
    <div class="<? if ($isPreview):?>col-md-12<?else:?>col-md-7<?endif;?>" id='story-wrapper'>
<?php endif;?>

        <div class="panel panel-default" id="parent-panel" style='padding-top:0px;margin-top:0px;'>
        <?php if (!$isPreview):?>
            <div class="panel-heading" id="panel-heading-story-view" style='padding-top:0px;margin-top:0px;'>                
              <h3 style='color:black;padding-top:0px;margin-top:0px;'>
                  <a style="text-decoration: none;" href='<?php echo node_link('story', $row);?>'>
                      <i class='<?php echo story_icon($storyType);?>'></i> 
                  <?php
                  //echo char_breadcumb($row['name'], 150);
                  echo $row['name'];
                  ?>
                  </a>
              </h3>
              <div style='font-size: 12px;'>
              <?php
                $point = isset($row['u']['point']) ? $row['u']['point'] : 0;
                ?>
                  
                <?php echo t('by',1);?>  <a href="<?php echo user_link($row['u']);?>" class="user-link">
                  <?php echo char_breadcumb($row['u']['name'], 20);?></a>
                  ,<b class="timeago" title="<?php echo convert_ts_to_js($row['ts']);?>"></b>
                  <i class="<?php echo get_icon('eye-open');?>"></i> <?php echo $row['counter']['v']; ?>
                 <i class="<?php echo get_icon('comment');?>"></i>
                  <?php if(isset($row['counter']['tc'])) echo $row['counter']['tc'];
                  		else echo "0";
                  ?>
              </div> <!--end row thong ke thong so-->
              <div style='font-size: 13px;'>
                  <i class="<?php echo get_icon('globe');?>"></i>
                  <span class="v_source">
                     <?php
                     echo t('source').':';
                     ?>
                      <span class="text">
                          <?php
                          $source = isset($row['source']) ? $row['source'] :t('default_source',1);
                          echo $source;
                          ?>
                      </span>
                  </span>
                   
              </div> <!-- end nguong-->
            </div>
            <?php endif;?>
           <div class="panel-body" style='padding-top:0px;'>
            <?php  if (!$isPreview): ?>     
                 <div class="row" style='padding-top:0px;margin-top:0px;'>
                      <!--show breadcum-->
                      <?php $vote = isset($row['counter']['vote']) ? $row['counter']['vote'] :0;
                       $vd = isset($row['counter']['vd']) ? $row['counter']['vd'] :0;
                       $spam = isset($row['counter']['spam']) ? $row['counter']['spam'] :0;
                       ?>
                      <div class="social-header"  
                           style="height: 52px; z-index: 200;">
                          <div class="col-md-3" id="collapse" data-votes = "<?php echo $vote;?>" data-vd = "<?php echo $vd;?>" data-spam="<?php echo $spam;?>">
                            <a title="<?php echo t("vote_up",1);?>" 
                            	data-iid = <?php echo $row['iid']."-vote-up";?>
                                 id = <?php echo $row['iid']."-vote-up";?>
                            	class=" cl_ajax has-tooltip vote-up cl_login" 
                                _cl_get_metadata="vote_story_success vote_success" 
                                href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=1">
                                <i class="vote-up-btn <?php echo get_icon('circle-arrow-up');?>"></i>
                              </a>
                              <span class='light-black vote_up' id="vote_up_count"><?php echo $vote;?></span>
                              
                              <a title="<?php echo t("vote_down",1);?>" 
                              	 data-iid = <?php echo $row['iid']."-vote-down";?>
                                 id = <?php echo $row['iid']."-vote-down";?>
                              	 class="cl_ajax has-tooltip vote-down cl_login"
                              	_cl_get_metadata="unvote_story_success unvote_success" 
                              	href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=4">
                                <i class="vote-down-btn <?php echo get_icon('circle-arrow-down');?>"></i>
                              </a>
                              <span class='light-black vote_down'  id="vote_down_count">              
                              <?php echo $vd?>
                              </span>
 
                             
                              <a title="<?php echo t("mark_as_spam",1);?>" 
                              	 data-iid = <?php echo $row['iid']."-mark-as-spam";?>
                                 id = <?php echo $row['iid']."-mark-as-spam";?>
                              	 class="cl_ajax has-tooltip cl_login mark-spam"
                              	_cl_get_metadata="mark_spam_success"
                              	style='color:red;' 
                              	href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=3">
                                <i class="mark-spam-btn <?php echo get_icon('remove');?>"></i>
                              </a>
                              <span class='light-black vote_spam'  id="mark_spam">              
                              <?php echo $spam?>
                              </span>
                          </div>
                          <div class="col-md-3"> <!-- facebook like -->
                              <div  style='padding-top:5px;'>
                                    <div class="fb-like" 
                                         data-href="<?echo SITE_URL;?><?php echo node_link('story',$row);?>"  
                                         data-layout="button_count" 
                                         data-action="like" 
                                         data-show-faces="true" 
                                         data-share="true">
                                    </div>
                              </div>
                          </div> <!-- End facebook like -->
                          
                          <div class="col-md-2"> 
                              <div class="g-plusone" data-size="medium"></div>
                          </div>
                          <div class="col-md-4">  
                              <div class="btn-group pull-right">
                               <a id =  "next" href='<?php
                                if(isset($rowN)){ 
                                	echo node_link('story', $rowN);
                                }else{
                                	echo '/';
                                } 
                               	?>'>
                               	<button  class='btn btn-sm has-tooltip btn-primary'  title="<?php echo t('prev_fun',1);?>"> 
            						<i class="<?php echo get_icon('chevron-left');?>"></i>
            					</button>
                               	</a>
                               	
                               	<a id ="prev" href='<?php
                                if(isset($rowP)){ 
                                	echo node_link('story', $rowP);
                                }else{
                                	echo '/';
                                } 
                               	?>'>
                               	<button class='btn btn-sm btn-primary has-tooltip'  title="<?php echo t('next_fun',1);?>"> <?php echo t('next',1);?>
                               		<i class="<?php echo get_icon('chevron-right');?>"></i>
                               	</button> 
                               	</a>
                             </div>   
                          </div>
                      
                      </div>
            
                      <!-- end span12 chua breadcum-->
                  </div> <!-- end row -->
            <?php endif;?>
        
        
            <div class="story-wrapper" >
                      <div class="align-center">
                          <?php if($storyType == 'flash-game'):?>
                          	<?php echo render_flash_game($row);?>
                          <?php endif;?>
                      
            	           <?php if($storyType == 'image'):?>
            					<?php $imgLink= story_image($row);
            					   $thumb_imgLink = story_thumb_image($row);
            					?>
            					<?php if ($imgLink != ''):?>
            						<?php if(!$row['is_iphone']):?>
            							<?php for ($i=0;$i<count($imgLink);$i++){?>
            								<?php 
            								$file_header = @get_headers($imgLink[$i]);
            								if($file_header[0] == 'HTTP/1.1 404 Not Found'){
            								    $imgLink[$i] = str_replace("1000/","",$imgLink[$i]);
            								}
            								Zend_Registry::set('ogImage',$imgLink[$i]);
            								Zend_Registry::set('Thumb_Image',$thumb_imgLink[0]);
            								//Zend_Registry::set('Thumb_Image','s.thaifun.net/thumb/thumb.jpg');
            								
            								?>
            								<img style="width: 616px;" id= "img" class="img-polaroid img-responsive" src="<?php echo $imgLink[$i];?>"></img>
            							<?php }?>
            						<?php else:?>
            						<?php 
            						        $file_header = @get_headers($imgLink[0]);
            								if($file_header[0] == 'HTTP/1.1 404 Not Found'){
            								    $imgLink[$i] = str_replace("1000/","",$imgLink[0]);
            								}
            								    Zend_Registry::set('ogImage',$imgLink[0]);
            								    Zend_Registry::set('Thumb_Image',$thumb_imgLink[0]);
            								   // Zend_Registry::set('Thumb_Image','s.thaifun.net/thumb/thumb.jpg');
            								?>
            						<img style="width: 616px;" id= "img" class="iphone img-polaroid img-responsive" src="<?php echo $imgLink[0];?>"></img>
            						<?php endif;?>
            					<?php else:?>
            						<?php echo t('image_not_found');?>
            					<?php endif;?>		
            				<?php elseif($storyType == 'video'): ?>
                				<?php 
                            		$imgLink = "http://img.youtube.com/vi/{$row['ytid']}/0.jpg";
                            		Zend_Registry::set('ogImage', $imgLink); 
                            		Zend_Registry::set('Thumb_Image',$imgLink);
                            		
                				?>
            				
            					<?php echo render_yt_embed_video($row['ytid'], 420, 315);?>
        					<?php elseif($storyType == 'multi-choice'):?>
            					<div class="col-md-12" id="collapse" data-votes = "<?php echo $vote;?>" data-vd = "<?php echo $vd;?>" data-spam="<?php echo $spam;?>">
                                    <a title="<?php echo t("pair_one",1);?>" 
                                    	data-iid = <?php echo $row['iid']."-vote-up";?>
                                         id = <?php echo $row['iid']."-vote-up";?>
                                    	class=" cl_ajax  cl_login btn btn-lg btn-danger col-md-6" 
                                        _cl_get_metadata="choose_pair_one_success vote_success" 
                                        href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=5">
                                        <?php echo $row['pair1'];?>
                                        <span class="fixed-top-counter"><?php echo '1';?></span>
                                      </a>
                                      <span class='light-black vote_up' id="vote_up_count" style="display:none;"><?php echo $vote;?></span>
                                      
                                      <a title="<?php echo t("pair_two",1);?>" 
                                      	 data-iid = <?php echo $row['iid']."-vote-down";?>
                                         id = <?php echo $row['iid']."-vote-down";?>
                                      	 class="cl_ajax choose-pair cl_login  btn btn-lg btn-danger col-md-6"
                                      	_cl_get_metadata="choose_pair__two_success vote_success" 
                                      	href="/user/relate?id=<?php echo $row['id'];?>&object=story&rt=6">
                                      	<?php echo $row['pair2'];?>
                                      	<span class="fixed-top-counter"><?php echo '1';?></span>
                                      </a>
                                      <span class='light-black vote_down'  id="vote_down_count" style="display:none;">              
                                      <?php echo $vd?>
                                      </span>
                                </div>
            					<?php $imgLink= story_image($row);
            					   $thumb_imgLink = story_thumb_image($row);
            					?>
            					<?php if ($imgLink != ''):?>
            							<?php for ($i=0;$i<count($imgLink);$i++){?>
            								<?php 
            								$file_header = @get_headers($imgLink[$i]);
            								if($file_header[0] == 'HTTP/1.1 404 Not Found'){
            								    $imgLink[$i] = str_replace("1000/","",$imgLink[$i]);
            								}
            								Zend_Registry::set('ogImage',$imgLink[$i]);
            								Zend_Registry::set('Thumb_Image',$thumb_imgLink[0]);
            								//Zend_Registry::set('Thumb_Image','s.thaifun.net/thumb/thumb.jpg');
            								
            								?>
            								<br/>
            								<br/>
            								<br/>
            								<img style="width: 616px;" id= "img" class="img-polaroid img-responsive separator-hight" src="<?php echo $imgLink[$i];?>"></img>
            							<?php }?>
            					<?php else:?>
            						<?php echo t('image_not_found');?>
            					<?php endif;?>	
        				
            				<?php endif;?>
            				
            			</div>
            		<?php 
            			if(isset($row['type'])){
                           if($row['type'] == 2 || $row['type'] == 3 )
            				{
            					//Nothing...
            				}else{
            					echo $row['content'];
            				}
            			}else{
            				if ($storyType != 'quote')
            					echo $row['content'];
            			}
            			?>
            			<?php if ($storyType == 'quote'):?>
            			<blockquote>
            		    	<p><?php echo $row['name'];?></p>
            		    	<small><?php if (isset($row['by']) && $row['by'] != ''):?><?php echo $row['by'];?><?php else:?>Láº·c danh<?php endif;?></small>
            		    </blockquote>
            			
            			<?php elseif ($storyType == 'quiz'):?>
            			<div style='padding-top:5px;'>
            				<a id='show-answer' href='javascript:void(0);' class='btn btn-sm btn-default'><?php echo t('view_answer',1);?></a>
            				<div id='answer' style='display:none;' class='well'>
            				<?php if (isset($row['answer']) && $row['answer'] != ''):?>
            				<?php echo $row['answer'];?>
            				<?php else:?>
            				    <?php echo t('dont_have_answer',1);?>
            				<?php endif;?>
            				</div>
            			</div>
            			<?php elseif ($storyType == 'link'):?>
            			<?php if (!isset($row['url'])) $row['url'] = '#';?>
            			<a href='<?php echo $row['url']?>'><?php echo $row['url']?></a>
            			<?php endif;?>
            			<?php if (isset($row['tags']) && count($row['tags']) > 0) :?>
                			<div class='separator'></div>
                			<div class='tags' style="clear: both;">
                    			<?php foreach ($row['tags'] as $tag) :?>
                    				<?php echo display_tag($tag);?>
                    			<?php endforeach;?>
                			</div>
            			<?php endif;?>
            </div><!-- End story wrapper -->	
        
            <?php if (!$isPreview):?>
            
                <div class='row' style="clear: both;">
                    <div class="panel panel-default" style="margin-top:-1px;">
                      <div class="panel-heading">
                        <h3 class="panel-title"><?php echo t('comment',2);?></h3>
                      </div>
                    </div>

                    <?php 
                    $url = str_replace("?_cl_modal_ajax=1", '', $_SERVER['REQUEST_URI']);
                    ?>
                    <!--<div id="fb-root"></div>-->
                        <div class="fb-comments" 
                            data-href="<?php echo SITE_URL . $url;?>" data-width="650" data-num-posts="10"></div>
                </div>
            <?php endif;?>
        
        </div>
        
        <?php /*Module relate stories*/?>
        <?php if (isset($this->list) && count($this->list['result']) > 0):?>
        <div class="panel panel-default">
        <div class="panel-heading" style="padding-top:5px; padding-bottom: 5px;">
            <h3 class="panel-title"><?php echo t('story_of_same_type',1);?></h3>
        </div>
        <div class="panel-body">
            <div class="row">
             <?php foreach ($this->list['result'] as $row):?>
             <div class="col-md-3">
                    <a style="text-decoration: none;" href="<?php echo node_link('story', $row);?>">
            		<?php if(isset($row['type'])):
            	               $storyType = story_type($row['type']);?>
            	                   
            	 	     <?php if($storyType == 'image'):?>
                                <?php 
            	                    $image =  STATIC_CDN . '/170/' . $row['url'];
            	                    $file_header = @get_headers($image);
                                ?>
                                <div class="filledImageRelate grow">
                                    <img class="img-polaroid img-responsive" src="<?php
                                            if($file_header[0] != 'HTTP/1.1 404 Not Found')
                                            {
                                                echo STATIC_CDN . '/170/' . $row['url'];
                                                $url = STATIC_CDN . '/170/' . $row['url'];
                                            }
                                            else
                                            {
                                                echo STATIC_CDN . $row['url'];   
                                                $url = STATIC_CDN . $row['url'];
                                            }
                                    ?>"
                                     <?php  /*Giup hien thi phan giua cua anh*/
        		                        /*(Filled image widget new|hot|vote)*/
        			                        	list($width, $height) = getimagesize(PUBLIC_FILES_UPLOAD_PATH . '/170/' . $row['url']);
        			                        	$heightFilledImage = 80;//height class filedImage img
        										$widthFilledImage = 100;
        			                        	
        			                        	//Get height (chieu dai thuc cua anh ty le
        			                        	// voi chieu dai cua khung chua anh)
        			                        	$heightFilledImageNew = $widthFilledImage * $height/ $width;
        			                        	
        			                        	$gap = ($heightFilledImageNew - $heightFilledImage)/2;
        			                        	if($gap > 0){
        			                        		echo "style = 'margin-top: -{$gap}px'";
        			                        	}
        			                        ?>
                                    >
                            </div>
            	                       
                        <?php endif;?>
                            
                        <?php if($storyType == 'video'):?>
                        	<?php 
                        		$imgLink = "http://img.youtube.com/vi/{$row['ytid']}/0.jpg";
                        	?>
                        		<img style="width: 616px;" class="lazy img-polaroid img-responsive" src="<?php echo $imgLink;?>">
                        		 <img class="tidypics-photo-start" width="35px" height="25px"
        					   			 style="left: 56px; position: absolute; top: 25px; width: 50px; height: 40px; cursor: pointer;" 
        					    	src="<?php echo ASSETS_CDN.'img/play_youtube.png'?>">
                        <?php endif;?>
                            
            	        <?php if($storyType == 'story'):?>
            	        	<div class = 'story_content story_content_related' style="border: 1px solid #BBBBBB;">
            	        	   <div class="content-relate">
        					       <?php echo  standardize_string_for_display($row['content'],14,11) ." ...";?>
        					   </div>
        					</div>
            	        <?php endif;?>
                            
                        <?php if($storyType == 'quote'):?>
                            <blockquote>
            		    	<p><a href='<?php echo node_link('story', $row);?>'><?php echo $row['name'];?></a></p>
            		    	<small><?php if (isset($row['by']) && $row['by'] != ''):?><?php echo $row['by'];?><?php else:?>Lặc danh<?php endif;?></small>
            		    	</blockquote>
                        <?php endif;?>
            		<?php endif;?>
            		</a>
            		<div class="clear"></div>
            		<div class="text-center">
            		    
                		<a style="text-decoration: none;" title="<?php echo $row['name'];?>" 
                            href="<?php echo node_link('story', $row);?>">
                			<b><?php
                    			echo char_breadcumb($row['name'], 46);
                               ?>
                             </b>
                		</a>
            		</div>
                </div>
                <?php endforeach;?>    
            </div>
        </div>
        </div>
        <?php endif;?>
      </div>


<?php if (!$isModal):?>
</div>
<?php if (!$isPreview):?>
	<div class="col-md-3 sidebar">
			<?php if (APPLICATION_ENV == 'development'):?>
				<div data-whereami='<? echo __FILE__;?>'></div>
			<?php endif;?>

				<div class="light-black-bg sidebar-nav col-md-12" style="min-height: 70px;">
    			<div class="alert alert-success alert-dismissable"><?php echo t('_help_like_fanpage',1)?>
				<?php if(!getenv("SITE")):?>
				<div class="fb-like-box" 
        				data-href="https://www.facebook.com/truyencuoihoibinet" 
        				data-width="The pixel width of the plugin" 
        				data-colorscheme="light" 
        				data-show-faces="false" 
        				data-header="true" 
        				data-stream="false" 
        				data-show-border="true">
    				</div>	
    				<?php elseif (getenv('SITE') == 'tf'):?>
    				<div class="fb-like-box" 
        				data-href="https://www.facebook.com/WaRiTiSaensukh" 
        				data-width="The pixel width of the plugin" 
        				data-colorscheme="light" 
        				data-show-faces="false" 
        				data-header="true" 
        				data-stream="false" 
        				data-show-border="true">
    				</div>	
    				<?php endif;?>
    				</div>
				</div>
                <div class="separator-high"></div>
				<div id ="top-user" data-url='/site/topuser' class='sand-ajax-widget'>
					</div>
				
				<div id ="new-image" data-url='/widget/new' class='sand-ajax-widget'>
					</div>
				<div class="social-header-widget affix-top">
    				<div id ="hot-image" data-url='/widget/hot' class='sand-ajax-widget'>
    					</div>
    				
    				<div id ="vote-image" data-url='/widget/vote' class='sand-ajax-widget'>
    					</div>
				</div>
				
			</div>
			<div class='col-md-2'>
			<?php if (APPLICATION_ENV == 'development'):?>
				<div data-whereami='<? echo __FILE__;?>'></div>
			<?php endif;?>
				<div class="sidebar-nav">
                    <?php echo get_conf('sidebar_ad1', '');?>					
				</div>
				<a style='position: fixed; right: 0px; bottom: 0px; color: white; font-size:250%;' 
				rel='nofollow' href='javascript:void(0);' onclick='window.location.href="/story/update?id=<?php echo $this->row['id'];?>"'>e</a>  
	</div>
    <?php endif;?>	
</div>		
<?php endif;?>
<?php
/* 
<?php $this->inlineScript()->captureStart();?>
$(document).ajaxComplete(function(){
    try{
        FB.XFBML.parse(); 
    }catch(ex){}
});
<?php $this->inlineScript()->captureEnd();?>
*/
?>