Dear <?php echo $this->name;?>, <br/>
<p>
<?php echo t("thank_you_for_registering_on_".DOMAIN."_to_use_all_of_our_features,_you_need_to_verify_your_email_address."),1 ?> </p>
<p><?php t("please_click_the_following_link_to_verify",1);?> <a href='<?php echo SITE_URL?>/user/verify-email?token=<?php echo $this->params['token']?>&uid=<?php echo $this->params['id']?>'><?php echo SITE_URL?>/user/verify-email?token=<?php echo $this->params['token']?>&uid=<?php echo $this->params['id']?></a><br/>
</p>
