	<div class="navbar navbar-default navbar-fixed-top" id='user_menu'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><i class='<?php echo get_icon('home');?>'></i></a>
        </div>
        
        <div class="navbar-collapse collapse">
        
          <ul class="nav navbar-nav" id='left-main-menu' >

              <li><a href="/"><?php echo t("home",1);?></a></li>
              <li class="active"><a href="/site/admin"><?php echo t("admin_home",1);?></a></li>
              <li><a href="/user/search" target="_blank"><?php echo t("user",1);?></a></li>
              <li><a href="/#apps"><?php echo t("mobile_app",2);?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
