<?php
$lu =  Zend_Registry::get('user');
$page = 'home';
if (isset($_REQUEST['page']))
    $page = $_REQUEST['page'];
if (Zend_Registry::isRegistered('page'))
    $page = Zend_Registry::get('page');
if(Zend_Registry::isRegistered('canonical'))
    $canonical = Zend_Registry::get('canonical');
else 
{
    $canonical = SITE_URL . $_SERVER['REQUEST_URI'];
}
?>
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# <?echo NS_PREFIX;?>: http://ogp.me/ns/fb/<?echo NS_PREFIX;?>#">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo Bootstrap::$pageTitle;?> - <?php echo DOMAIN;?></title>
<meta name="description" content="<?php echo Bootstrap::$pageDesc;?>" />
<link rel="canonical" href="<?php echo $canonical;?>" />
<meta property="og:url" content="<?php echo $canonical;?>"/>
<?php if(getenv('SITE') == false):?>
<link rel="shortcut icon" href="<?php echo SITE_URL;?>/hoibinet1.ico" />
<?php elseif (getenv('SITE') == 'tf'):?>
<link rel="shortcut icon" href="<?php echo SITE_URL;?>/b.ico" />
<?php endif;?>
<meta property="og:title" content="<?php echo Bootstrap::$pageTitle;?>"/>
<?php 
/*
 <meta property="og:site_name" content=" <?php echo get_conf('site_name', '<?php echo SITE_URL; ?>');?>"/>
 <meta property="og:type" content="<?php echo get_conf('type');?>" />
 */
?>


<meta property="og:site_name" content="<?php echo DOMAIN;?>"/> 

<meta property="og:description"  content="<?php echo t('click_to_view_and_comment');?>"/>

<meta property="fb:app_id" content="<?php echo get_conf('fb:app_id', FB_APP_ID);?>"/> <!--  define facebook app ID -->
<?php $ogImage = Zend_Registry::isRegistered('ogImage') ? Zend_Registry::get('ogImage')  : 's.thaifun.net/thumb/thumb.jpg';
$thumb_Image = Zend_Registry::isRegistered('Thumb_Image') ? Zend_Registry::get('Thumb_Image')  : 's.thaifun.net/thumb/thumb.jpg';
?>

<meta property="og:image" content="<?php echo $thumb_Image;?>" />


<?php if ($page == 'story/index/view'):?>
<meta property="og:type" content="<?php echo t('opengraph_type');?>" /> 
<meta property="<?php echo t('opengraph_full_image');?>" content="<?php echo $ogImage;?>" />
<?php endif;?>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<?php
/* 

<?php //if (APPLICATION_ENV == 'development') :?>
<link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/bootstrap-2.3.2/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/bootstrap-2.3.2/css/bootstrap-responsive.min.css">

<link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/fontawesome-3.11/css/font-awesome.css">
<link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/fontawesome-3.11/css/font-awesome-ie7.css">
*/
?>
<link href="<?php echo SAND_ASSETS_CDN;?>/css/reset.css" rel="stylesheet">

<link href="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo SAND_ASSETS_CDN;?>/css/common.css" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo ASSETS_CDN;?>/css/styles.css" media="screen" rel="stylesheet" type="text/css">
<?php
/* 
<link href="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/css/bootstrap-glyphicons.css" rel="stylesheet">
*/
?>
	 
<link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/resources/css/jquery.toastmessage.css"
	rel="stylesheet" type="text/css" />
<link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/lazyload/resources/style.css"
	rel="stylesheet" type="text/css" />

	<?php
/*
 //else
 //<link href="<?php echo ASSETS_CDN . "css/_v" . JSVERSION . ".css"?>" media="screen" rel="stylesheet" type="text/css" >
 // endif;
 *
 */
?>

<style>
div.navbar ul.breadcrumb>li {
	min-height: 30px;
	padding-top: 10px;
}
</style>

<script type='text/javascript'>
<?php echo $this->render('widget/php-to-js.phtml');?>
</script>

</head>
<body>

	<div id="ajaxModal" class="modal fade" 
        tabindex="-1" role="dialog" aria-labelledby="ajaxModalLabel" aria-hidden="true"
        role="dialog">  
        <div class="modal-dialog">
         <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h4 id="ajaxModalLabel"></h4>
          </div>
          
          <div class="modal-body">
          </div>
          
          <div class="modal-footer" style='display:none;'>
              <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo t('close',1);?></button>
              <button class="btn btn-primary" id="yes_help_thanks" ><i class='<?php echo get_icon('ok');?>'></i> <?php echo t('yes', 1);?></button>
          </div>
         </div>
        </div>
	</div>
	
	<!-- if IS_GUEST only showing GUEST MENU -->
	<?php echo $this->render("covervd_menu.phtml");?>
	
	<?php if (APPLICATION_ENV == 'development'):?>
	<div class='sand-dev-info alert alert-info' style='display:none;'>
	    <?php $p = explode('/', $page);?>
	    <b>Action:</b> <?php echo $page;?> 
	    <br/>
	    <b>Layout script:</b> <span class='sand-dev-selecttext' ><?php echo __FILE__;?></span>
	    <br/>
	    <b>Controller File:</b> <span class='sand-dev-selecttext'><? echo APPLICATION_PATH;?>/modules/<?php echo $p[0]?>/controllers/<?php echo ucwords($p[1])?>Controller.php</span>
	</div>
	<?php endif;?>
		

	<div class='container' style='min-height:450px;'>
		<?php echo $this->layout()->content;?>
	</div> <?php //end body?>
	
	
	<div class="container"  style="background-color:#222222;padding:30px;margin-top:30px; ">
		<?php if(!getenv("SITE")):?>
		<footer>
			<p style='color:#888888;'>&copy; <b><?php echo preg_replace('/^http:\/\//', '', SITE_URL)?> 2007-2013</b></p>
				<a title='<?php echo t('home');?>' href="/" style='color:white;'><i style='color:white;' class='<?php echo get_icon('home');?>'></i></a>
				
				<a style='color:#888888;'href="<?php echo category_link('video');?>"><?php echo t('video', 1);?></a>
				|
				<a style='color:#888888;' href="<?php echo category_link('image');?>"><?php echo t('image', 1);?></a>
				|
				<a style='color:#888888;' href="<?php echo category_link('story');?>"><?php echo t('story', 1);?></a>
				|
				<a style='color:#888888;' href="<?php echo category_link('link');?>"><?php echo t('link', 1);?></a>
				|
				<a style='color:#888888;' href="<?php echo category_link('quiz');?>"><?php echo t('fun_quiz', 1);?></a>
				|
				<a style='color:#888888;' href="<?php echo category_link('flash_game');?>"><?php echo t('flash_games', 1)?></a>
				|
				<a style='color:#888888;' href="/tag"><?php echo t("tag_cloud",2);?></a>
				|
				<a style='color:#888888;' href="/do-vui"><?php echo t("fun_quiz",2);?></a>
				|
				<a style='color:#888888;' href="http://romajidesu.com">Japanese Vietnamese Online Dictionary</a>
		</footer>
		<?php elseif (getenv('SITE') == 'tf'):?>
		<footer>
		<div style='color:#888888; text-align: center;'>			
				<a title='<?php echo t('home');?>' href="/" style='color:white;'><i style='color:white;' class='<?php echo get_icon('home');?>'></i></a>
				
				<a style='color:#888888;'href="/page/about.html"><?php echo t('About', 1);?></a>
				|
				<a style='color:#888888;' href="/page/terms.html"><?php echo t('Terms', 1);?></a>
				|
				<a style='color:#888888;' href="/page/contact.html"><?php echo t('Contact', 1);?></a>
		</div>
		<div style='color:#888888; text-align: center;'>
		      <span style='color:#888888;'><?php echo t('_Thaifun_on')?>: </span>  
		      <a style='color:#888888;'target="_blank" href="https://www.facebook.com/thaifun.net">Facebook</a>
		      |
		      <a style='color:#888888;'target="_blank" href="https://twitter.com/thaifunnet">Twitter</a>
		      |		    
		      <a  style='color:#888888;' target="_blank" href="https://itunes.apple.com">iOS</a>
		      |
			  <a   style='color:#888888;' target="_blank" href="https://play.google.com">Android</a>
		</div>
		<div style='color:#888888; text-align: center;'>
		<p style='color:#888888;'>&copy; <b>2013 <?php echo preg_replace('/^http:\/\//', '', SITE_URL)?></b></p>
		</div>				
		</footer>
		<?php endif;?>
		
	</div>


	<script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery.js"></script>

    <script src="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/js/bootstrap.min.js"></script>			
	<script
		src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/javascript/jquery.toastmessage.js"
		type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/utils.js"	type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.form.js"
		type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.fitvids.js" type="text/javascript"></script>

	<script type="text/javascript"
		src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/src/jquery.tokeninput.js"></script>
	<link rel="stylesheet" type="text/css"
		href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/styles/token-input-facebook.css" />
	<script
		src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax_metadata_config.js"
		type="text/javascript"></script>
	<script
		src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.timeago.js"
		type="text/javascript"></script>
		
		<!-- Update tiny_mce 4.0.2  -->
	<?php /*<script type="text/javascript" src="<?php echo SAND_ASSETS_CDN;?>/js/tinymce/tinymce_4.0.2/jscripts/tiny_mce/tinymce.min.js"></script> */ ?>
	<?php // DOWNGRADE TINIMCE TO 3.5.2?>
	<script type="text/javascript"
		src="<?php echo SITE_URL;?>/tinymce/tinymce_3.5.2/jscripts/tiny_mce/tiny_mce.js"></script>
	<script src="<?php echo ASSETS_CDN;?>/js/vi.js"></script>
		
	<?php /* <script src="<?php echo ASSETS_CDN;?>/js/init_tinymce_4.0.2.js" type="text/javascript"></script> */ ?>
	<?php if($page != 'story/index/view' && $page != 'site/index/index'):?>
		<script src="<?php echo ASSETS_CDN;?>/js/init_tinymce.js" type="text/javascript"></script>
	<?php endif;?>
	
	<?php /*
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/comment.js"
		type="text/javascript"></script>
	*/?>

	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax.js"
		type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/site_common.js"
		type="text/javascript"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/callbacks.js" type="text/javascript"></script>
		
	<script src="<?php echo ASSETS_CDN;?>/js/site.js" type="text/javascript"></script>
	
	<?php
	/* 
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.ui.datepicker.js"
		type="text/javascript"></script>
		
	<script
		src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/autoresize.jquery.js"
		type="text/javascript"></script>
    */
	?>

	<script
		src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/lazyload/lazyload.js"></script>
	
		<?php
		/*
		 * else :?>
		 <script type="text/javascript" src="<?php echo ASSETS_CDN."/js/_v".JSVERSION.".js";?>"></script>
		 <?php endif;
		 *
		 */
		?>

		<?php echo $this->headScript();?>
		<?php print $this->inlineScript();?>
<?php if (APPLICATION_ENV != 'development'):?>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&amp;lang=th">
</script>
   
<?php endif;?>

<?php if (APPLICATION_ENV != 'developments'):?>
<div id="fb-root"></div>
		
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<?php echo GA_ID?>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<?php Endif;?>

<?php 
/*

<script type="text/javascript">
var interval;

$(function()
{
    interval=setInterval("updateActiveElement();", 50);
});
 
function updateActiveElement()
{
    if ( $(document.activeElement).attr('id')=="fbframe" )
    {
        clearInterval(interval);
        iflag=1;
    }    
}
</script>
         
 
       
       
<div style="overflow: hidden; width: 10px; height: 12px; position: absolute; filter:alpha(opacity=0); -moz-opacity:0.0; -khtml-opacity: 0.0; opacity: 0.0;" id="icontainer">
        <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fvieted.com%2F&amp;layout=standard&amp;show_faces=false&amp;width=450&amp;action=like&amp;font=tahoma&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:50px; height:23px;" allowTransparency="true" id="fbframe" name="fbframe"></iframe>
</div>
   
   
<script>
    var iflag = 0;
    var icontainer = document.getElementById('icontainer');    
    var standardbody=(document.compatMode=="CSS1Compat")? document.documentElement : document.body //create reference to common "body" across doctypes
   
   
   
    function mouseFollower(e){

    if (window.event)
    { // for IE
        icontainer.style.top = (window.event.y-5)+standardbody.scrollTop+'px';
        icontainer.style.left = (window.event.x-5)+standardbody.scrollLeft+'px';
    }
    else
    {
        icontainer.style.top = (e.pageY-5)+'px';
        icontainer.style.left = (e.pageX-5)+'px';
    }
 
    }
    document.onmousemove = function(e) {
        if (iflag == 0) {mouseFollower(e);}
    }
 
    </script>
 */
 ?>
</body>
</html>

