<style>
@media (max-width: 1000px) {
    .navbar-header {
        float: none;
    }
    .navbar-toggle {
        display: block;
    }
    .navbar-collapse {
        border-top: 1px solid transparent;
        box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);
    }
    .navbar-collapse.collapse {
        display: none!important;
    }
    .navbar-nav {
        float: none!important;
        margin: 7.5px -15px;
    }
    .navbar-nav>li {
        float: none;
    }
    .navbar-nav>li>a {
        padding-top: 10px;
        padding-bottom: 10px;
    }
    .container-fluid{
    	background:#333;
    }
    
    .container>.navbar-header,
	.container>.navbar-collapse
	{margin-right:0;margin-left:0}
	
	.navbar-fixed-top, .navbar-fixed-bottom {
    position: fixed;
    }
    .navbar-collapse.in {
		overflow-y: auto;
		max-height: 340px;
		padding-right: 15px;
		padding-left: 15px;
		overflow-x: visible;
		}
	.navbar-nav .open .dropdown-menu {
		position: static;
		float: none;
		width: auto;
		margin-top: 0;
		background-color: transparent;
		border: 0;
		box-shadow: none;
		}
	.navbar-right .dropdown-menu {
		left: 0;
		right:auto;
		}
	.dropdown-menu>li>a
	{	
		color:#999;
	}
	.dropdown-menu>li>a:hover{
		
	}
}
@media (max-width: 990px) {
 #count-vote-comment{
 	display:none;
 }

}
.navbar-inner {
background: #2b2b2b;
background-image: none;
background-repeat: repeat-x;
border-color: none;
filter: none;
}
</style>

<?php echo sand_dev_info_phtml(__FILE__);?>
<?php $filter = $this->filter;
//v($filter);
?>
<?php $lu = Zend_Registry::get('user');?>
<!-- Begin Nav bar-->
<nav class="navbar navbar-fixed-top navbar-inverse" id='user_menu' role="navigation" >
	 <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><i class='<?php echo get_icon('home', $type = 'glyph');?>'></i></a>
        </div>
        
        <div class="navbar-collapse collapse" id="navigation">
        
          <ul class="nav navbar-nav" id='left-main-menu' >
				<?php $menu = Zend_Registry::isRegistered('active_menu') ? Zend_Registry::get('active_menu') : 'home';
				?>
					
			   <li class="dropdown hover"><a href="/" title='<?php echo t('home_page',1);?>'><i style='color:white;' class='icon-home'></i></a></li>
			   <li class='dropdown hover <?php if ($menu === 'new'):?>active<?php endif;?>'>
				   <a href="/new" title='<?php echo t('new',1);?>'><i class='<?php echo get_icon('time');?>'>
				       </i> <b><?php echo t('new',2);?></b>
				   </a>
			   </li>
  			   <li class='dropdown hover <?php if ($menu === 'hot'):?>active<?php endif;?>'>
					   <a href="/hot" title='<?php echo t('hot',1);?>'><i class='<?php echo get_icon('star');?>'>
					       </i> <b><?php echo t('hot',2);?></b>
					   </a>
			   </li>
			   
			   <li class='dropdown hover <?php if ($menu === 'best'):?>active<?php endif;?>'>
				   <a href="/best" title='<?php echo t('best',1);?>'><i class='<?php echo get_icon('heart');?>'>
				       </i> <b><?php echo t('best',2);?></b>
				   </a>
			   </li>
				<?php
				/* 
				<li <?if ($menu == 'picks'):?>class='active'<?endif;?>><a href="/picks" title='Chọn bởi đội ngũ admin'><i class='icon-pencil'></i> Picks</a></li>
				*/
				?>
			   <li class='dropdown hover <?php if ($menu === 'vote'):?>active<?php endif;?>'>
				   <a href="/vote" title='<?php echo t('sorted_desc_by_votes_number',1);?>'><i class='<?php echo get_icon('pencil');?>'>
				       </i> <b><?php echo t('vote',1);?></b>
				   </a>
			   </li>
				<li class="dropdown hover">
            		<a href="/" class="dropdown-toggle" data-toggle="dropdown"><b><?php echo t('more',1);?></b><b class="caret"></b></a>
	                <ul class="dropdown-menu">
	                  <li><a href="<?php echo SITE_URL.'/'.nav_link($filter,'2');?>"><i class='<?php echo story_icon('image');?>'></i> <?php echo t('fun_picture',1);?></a></li>
	                  <li><a href="<?php echo SITE_URL.'/'.nav_link($filter,'3');?>"><i class='<?php echo story_icon('video');?>'></i> <?php echo t('fun_video',1);?></a></li>
	                  <li><a href="<?php echo SITE_URL.'/'.nav_link($filter,'1');?>"><i class='<?php echo story_icon('story');?>'></i> <?php echo t('fun_story',1);?></a></li>
					  <li><a href="<?php echo SITE_URL.'/'.nav_link($filter,'4');?>"><i class='<?php echo story_icon('quiz');?>'></i> <?php echo t('fun_quiz', 2);?></a></li>
	                  <?php
	                  /*
	                   * 
					  <li><a href="/hot/flash-game"> <i class='<?php echo story_icon('flash-game');?>'></i> <?php echo t('flash_games', 2)?></a></li>
					  <li><a href="/hot/link-vui"> <i class='<?php echo story_icon('link');?>'></i><?php echo t('fun_link',1);?></a></li>
                	  <li><a href="/hot/cau-noi-noi-tieng"> <i class='<?php echo story_icon('quote');?>'></i> <?php echo t('quote',2);?></a></li>
	                   */ 
	                  ?>
	                </ul>
          		</li>
				<li id="upload_btn" class="dropdown hover" style='padding-left:10px;'>
            		<button  class='btn btn-primary dropdown-toggle' data-toggle="dropdown" style='color:white;'>
            		  <i class='<?php echo get_icon('arrow-up');?>'></i> <?php echo t('upload',1)?>
            		</button>
	                <ul class="dropdown-menu"  >
		                  <li>
		                      <a class='cl_login' href="/story/new?type=<?php echo story_typeint('image');?>"> 
		                      <i class='<?php echo story_icon('image');?>'></i>
		                      <?php echo t('fun_picture',1);?></a>
		                  </li>
		                  <li>
		                      <a href="/story/new?type=<?php echo story_typeint('video');?>">
		                       <i class='<?php echo story_icon('video');?>'></i>
		                       <?php echo t('fun_video',1);?></a>
		                  </li>
		                  <li>
		                      <a href="/story/new?type=<?php echo story_typeint('story');?>"> 
		                      <i class='<?php echo story_icon('story');?>'></i>
		                      <?php echo t('fun_story',1);?></a>
		                  </li>
		                  <li>
		                      <a href="/story/new?type=<?php echo story_typeint('multi-choice');?>"> 
		                      <i class='<?php echo get_icon(story_icon('multi-choice'));?>'></i>
		                      <?php echo t('multi_choice_question',1);?></a>
		                  </li>

	                </ul>
          		</li>
          		
				<li id="create_btn" style='padding-left:10px;' class="dropdown hover">
            		<button  class='btn btn-success dropdown-toggle' data-toggle="dropdown" style='color:white;'>
            		  <i class='<?php echo get_icon('edit');?>'></i> <?php echo t('create',1)?>
            		</button>
				<ul class="dropdown-menu"  >
		                  <li>
		                      <a href="/story/new?type=<?php echo story_typeint('image');?>&iphone=1"
		                      class='cl_login'
		                      > 
		                          <i class='<?php echo story_icon('image');?>'></i> <?php echo t('iphone_chat',1);?></a>
		                  </li>
		                  <li>
		                      <a class='cl_login' href='/site/rage-maker' > <i class='<?php echo story_icon('story');?>'></i> <?php echo t('rage_maker',1);?></a>
		                  </li>
	                </ul>
	                
          		</li>
<?php 
/**
 * 
          		<li class="drop down">
                    <ul id='upload_menu' class="dropdown-menu" style='font-size:normal; margin-left: 2px; float: left'>
	                  <li><a href="/story/new?story_type=image"> <i class='<?php echo story_icon('image');?>'></i><?php echo t('fun_picture',1);?></a></li>
	                  <li><a href="/story/new?story_type=video"> <i class='<?php echo story_icon('video');?>'></i><?php echo t('fun_video',1);?></a></li>
	                  <li><a href="/story/new?story_type=story"> <i class='<?php echo story_icon('story');?>'></i><?php echo t('fun_story',1);?></a></li>
	                </ul>
                </li>
              		
 */
?>
              		
              		
				</ul>
				
			<?php /*<!--/.nav-collapse -->
			<!-- search form -->
			<!-- <form class="navbar-search pull-left">
				<input type="text" class="search-query" placeholder="Search">
			</form> -->*/?>
			<?php /*<!-- Update search google engine site 31.7.2013 -->*/ ?>
			<ul class="nav navbar-nav navbar-right" style='padding-left:10px;'>
				<li id="c_uname" class="dropdown hover" style="display:none">
						<button data-toggle="dropdown" class="btn btn-success dropdown-toggle" href="#" id="drop1" style="color: white;"><b  class="caret"></b> </button>
						<ul aria-labelledby="drop1" role="menu" class="dropdown-menu" id = 'user_menu_nav'>
							<?php ///user/update?id={$lu['id']};&_cl_step=account ?>
							<li><a id='setting_menu' href="#" tabindex="-1"><?php echo t('settings',1);?></a>
							</li>
							<?php //user/$userIid?>
							<li><a id="prof_page" href="#" tabindex="-1"><?php echo t('my_posts', 1);?></a></li>
							<li><a href="/user/logout" style='color:red;font-weight:bold;' tabindex="-1"><i class='<?php echo get_icon('logout');?>'></i> <?php echo t('logout', 1);?></a></li>
						</ul>
					</li>
        			<li id="c_login" style='display:none;margin-left:-15px;'>
        			
        				<a name="login"  value="Login"
        				   class="modal_ajax modal-login" on_modal_shown="rebind_ajax_form"
        				   href="/user/login?b=/"><button class="btn btn-success"><?php echo t('login', 3);?></button></a> 
        			</li>
			</ul>
		<ul class="nav navbar-nav navbar-right" style="padding:0 10px 0 10px;" >
		<li>
                           
			 <div class="gs-result gs-webResult" id="gse-custom-input">
    			<form action="/search" class="inputForm navbar-search pull-left" id="cse-search-box" method="get">
                            <input class="form-control" type="text"  
                            autocomplete="off" name="q" />                    
                          <!--style="background-color: white; background-image: url(http://www.google.com/cse/intl/en/images/google_custom_search_watermark.gif); background-position: 0% 50%; background-repeat: no-repeat no-repeat; border: 1px solid rgb(126, 157, 185); padding: 2px;"-->
                    <input type="hidden" name="cx" value="004332691448629203100:a4unod_up6u" /> 
                    <input type="hidden" name="cof" value="FORID:10" />
                    <input type="hidden" name="ie" value="UTF-8" />
    			</form>
			</div>  
                </li>
			</ul>
			
        </div><!--/.nav-collapse -->
        </div>
    </nav>
			
		<!--
<script type="text/javascript">
  var googleSearchIframeName = "cse-search-results";
    var googleSearchFormName = "cse-search-box";
    var googleSearchFrameWidth = 100;
    var googleSearchDomain = "www.google.com.th";
    var googleSearchPath = "/cse";
</script>
-->
<?php //$this->headScript()->appendFile('http://www.google.com/afsonline/show_afs_search.js','text/javascript'); ?>
