<?$base = '/rage/';?>
<?php $story = $this->storyRegistered; ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Rage Maker</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="<?echo $base;?>css/jquery-ui.css?v=1.0.1" type="text/css" />

<script type="text/javascript" src="<?echo $base;?>js/jquery/jquery.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>js/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jQuery.cssTransform.Patch.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/cp_depends.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/excanvas.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/CanvasWidget.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/CanvasPainter.full.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.batchImageLoad.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.autogrow.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.flickr-1.0-min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/interface.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.blockUI.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/colorpicker.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.repeatedclick.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.imgDrop.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.getimagedata.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/base64.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/canvas2image.js"></script>
<?php 
    $lang = getenv('LANGUAGE');
?>


<script type="text/javascript" src="/site/rage-translations"></script>

<script type="text/javascript">
function capitaliseFirstLetter(string)
{
    return string.charAt(0).toUpperCase() + string.slice(1);
}

var t = function(str, format)
{
    var r = str;
    if (typeof rageTranslations[str] != 'undefined')
        r = rageTranslations[str]; 
    //convert to Capital letter
    if (typeof format != 'undefined' && format == 1)
        return capitaliseFirstLetter(r); 
    else
        return r;
};
var SITE_URL = '<?php echo SITE_URL;?>'
var edit = false;
var img_url = '';
var storyId = '';
<?php if($story != '' || $story != null): ?>
    edit = <?php echo $this->isEdit;?>;
    img_url  = '<?php echo STATIC_CDN.$story['url'];?>';
    storyId = '<?php echo $story['id'];?>';
<?php endif;?>
</script>

<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/rage.unmin.js"></script>
<script type="text/javascript">
<?php if($story != ''):?>
$(document).ready(function(){
    $("#rage-help").click(function(e) {
        $('html, body').scroll({
            scrollTop: $("#help-box").offset().top
        },500);
    });
});
<?php endif;?>
</script>
<script type="text/javascript" src="<?echo $base;?>js/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/validate.js"></script>
<link href="<?echo $base;?>ragecomic/css/style.css?v=1.0.0" rel="stylesheet" type="text/css" />
<link href="<?echo $base;?>ragecomic/css/colorpicker.css?v=1.0.0" rel="stylesheet" type="text/css" />
<link href="<?echo $base;?>ragecomic/css/start/jquery-ui-1.7.2.custom.css?v=1.0.0" rel="stylesheet" type="text/css" />
<script type="text/javascript">
	var siteUrl = "<?echo $base;?>";

	var stylesheet_directory =  "<?echo $base;?>ragecomic/";
	var imageTypeId = 84;
	RageComic.initialize({packRoot: stylesheet_directory,
			      siteUrl: siteUrl,
			      submissionUrl: siteUrl + "save",
			      imageTypeId: imageTypeId});
</script>
<script type="text/javascript">
function readCookie(name) {
    var nameEQ = name + "=";
    var ca = document.cookie.split(';');
    for(var i=0;i < ca.length;i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1,c.length);
        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
    }
    return null;
}
var uid = readCookie("_cl_uid");
if (uid ==null || uid =="" || uid == 0 || uid =="undifined")
{
	window.location.href = "/user/login";
}
</script>

</head>
<body class="MEME">

        <div style="width:640px;margin:0 auto;">
          <div id="pane2" style="margin: 20px 0; width: 640px; position: relative; min-height: 0px;">
               <div class="">
                <?php echo t('click_image_to_insert_to_drawing_area',1);?>
               </div>
          
        
            <div id="blank_content">
              <div class="sharedaddy"></div>
              <div id="memebaseSubmitFormContainer"></div>
              <div>
                <div class="dock" id="toolbar">
                  <div class="dock-container" title=<?php echo t("click_to_add_it_to_the_canvas",1);?>></div>
                </div>
              </div>
              <div id='promptContainer' title=<?php echo t('import_image',1);?>>
                <div><strong>URL: </strong>
                  <input type='text' id='txtImportUrl' value='' />
                </div>
                <p class='errorText'></p>
                <p> <?php echo t('enter_the_URL_to_an_image_you_would_like_to_import.This_could_be_another_rage_comic_or_anything_else.');?></p>
              </div>
              <div id='flickrContainer' title='Import image from Flickr'>
                <label><strong><?php echo t('enter_keyword',1);?>: </strong></label>
                <input type="text" value="" id="flickrSearchTerm" />
                <p id="flickrHelpText"> <?php echo t('search_for_an_image_on_flickr.For_example:"cat_white_background"',1);?> </p>
                <p style="display:none" id="flickrLoading"></p>
                <div id="flickrResult"></div>
              </div>
              <div id='startUpMessageContainer' title=<?php echo t('pro_tip',1);?>></div>
              <div id='exportContainer' title=<?php echo t('export_meme_image?',2);?>>
                <div>
                  <div style='float: left'><img src="<?echo $base;?>ragecomic/images/messageTroll.png" tppabs="ragecomic/images/messageTroll.png"/></div>
                  <div> <?php echo t('finalize?_You_wont_be_able_to_modify_your_masterpiece_further.',1);?><br/>
                    <br/>
                    <?php echo t('in_the_next_step,_you_will_be_able_to_submit_your_Rage_Comic_to_Meme.',1);?> <br/>
                    <br/>
                    <b><?php echo t('meme_maker',1);?></b><br/>
                    <?php echo t('submit_meme_to_mememaker_gallery',1);?></div>
                  <div style='clear: both'></div>
                </div>
              </div>
              <div id="canvasContainer">
                <div id="controllers" class="ui-widget-header ui-corner-all">
                  <div id="templateController" class="controllerSubset" style="border-left: none; padding-left: 3px;">
                    <select id="drpPacks" title=<?php echo t('template_set',1);?>>
                    </select>
                  </div>
                  <div id="toolsController" class="controllerSubset"> <strong></strong> <span title=<?php echo t('add_text_box',1);?> id='addTextCtrl' class='menuIcon'><img src="<?echo $base;?>ragecomic/images/text_dropcaps.png" alt="text_dropcaps" align="absmiddle" /></span> <span title=<?php echo t('import_image_from_URL',1);?> id='importImage' class='menuIcon'><img src="<?echo $base;?>ragecomic/images/photo_add.png" alt="photo_add" align="absmiddle" /></span> <span title=<?php echo t('select_brush_color',1);?> id="customWidget" class='menuIcon'><img src="<?echo $base;?>ragecomic/images/color_wheel.png" alt="color_wheel" align="absmiddle" /></span> 
                  <span title=<?php echo t('select_brush_size',1);?> id="brushSize" class='menuIcon'>
                  	<img src="<?echo $base;?>ragecomic/images/paintbrush.png" alt=<?php echo t('paintburhs',1);?> align="absmiddle" />
                  	<div id="brushSizeSlider"></div>
                  </span> 
                  <span title=<?php echo t("undo_last_brush_or_'send_to_back'_action",1);?> id="undoBrush" class='menuIcon'>
                  	<img src="<?echo $base;?>ragecomic/images/arrow_undo.png" alt="arrow_undo" align="absmiddle"/></span> 
                  </div>
                  <div id="panelController" class="controllerSubset" style="float: right;"> 
        	          <span title=<?php echo t('add_row',1)?> id='addBlankRow' class='menuIcon'>
        	          	<img src="<?echo $base;?>ragecomic/images/add.png" alt=<?php echo t('add',1);?> align="absmiddle"/>
        	          </span>
        	          <span title=<?php echo t('add_blank_row',1);?> id='addFrameCtrl' class='menuIcon'>
        	          	<img src="<?echo $base;?>ragecomic/images/add.png"  alt=<?php echo t('delete');?> align="absmiddle"/>
        	          </span> 
        	          <span title=<?php echo t('delete_last_row',1);?> id='removeFrameCtrl' class='menuIcon'>
        	          	<img src="<?echo $base;?>ragecomic/images/delete.png"  alt=<?php echo t('delete');?> align="absmiddle"/>
        	          </span>
        	           
                  </div>
                  <span title=<?php echo t('export_canvas',1);?> id='exportCanvas' class='menuIcon'><img src="<?echo $base;?>ragecomic/images/disk.png" alt="disk" align="absmiddle" style=" margin-left:10px;"/></span>
                  
                  <div style="clear: both"></div>
                </div>
                <div id='drawingCanvasContainer'>
                  <canvas id="drawingCanvasInterface"></canvas>
                  <canvas id="drawingCanvas"></canvas>
                </div>
                <img src="<?echo $base;?>ragecomic/images/watermark.png" alt="watermark" id="watermark" style=" display:none;position:relative; left:50px; bottom:100px;" /> </div>
            </div>
           
          </div>
        </div>
        <div class="slide_likebox" style="background: url(<?php echo ASSETS_CDN.'/images/fb.png'?>) no-repeat !important;">
            <div style="color: rgb(255, 255, 255); padding: 8px 5px 0pt 50px;">
            <div class="FB_Loader"></div>
                <span>
                <?php if(getenv('SITE') == 'tf'):?>
                    <iframe src="http://www.facebook.com/plugins/likebox.php?href=http://https://www.facebook.com/thaifun.net&amp;width=198&amp;colorscheme=light&amp;show_faces=true&amp;stream=false&amp;header=false&amp;height=368" 
                        scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:198px; height:368px;" 
                        allowTransparency="true">
                    </iframe>
                <?php else:?>
                    <iframe src="http://www.facebook.com/plugins/likebox.php?href=http://www.facebook.com/truyencuoihoibinet&amp;width=198&amp;colorscheme=light&amp;show_faces=true&amp;stream=false&amp;header=false&amp;height=368" 
                        scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:198px; height:368px;" 
                        allowTransparency="true">
                    </iframe>
                <?php endif;?>   
                </span>
            </div>
        </div>
        <div class="homeUrlBox button-help">
           <a title='<?php echo t('home');?>' href="<?php echo SITE_URL;?>" style='color:white;'>
               <i style='color:white;' ><?php echo t('home');?></i>
           </a>
        </div>
        <div class="helpBox">
           <a  id="rage-help" href="#help-box" title = "<?php echo t('this_page_will_help_you_how_to_use_rage-maker_tool');?>" 
              class="button-help">
            <i style='color:white;'><?php echo t('help_page',1);?></i>
           </a>
        </div>
        <div class="help-box" id="help-box" >
            <h3><?php echo t('rage_maker_guide',1);?></h3>
            <ul>
            <?php $help_text = get_conf('help_text');
            if($help_text != ''):
            foreach ($help_text as $key => $val):
            ?>
                <li><?php echo $val;?></li>
            <?php endforeach;?>
            <?php else:?>
                <?php echo t('there_dont_have_any_help_informations',1);?>
            <?php endif;?>
            </ul>
        </div>
        <img alt="story_img_url" id="story_img_url" style=" display:none;" src="<?php echo STATIC_CDN.$story['url'];?>" />
</body>
</html>
