<?php 
    $lu =  Zend_Registry::get('user');
    $page = 'home';
    if (isset($_REQUEST['page']))
        $page = $_REQUEST['page'];
    if (Zend_Registry::isRegistered('page'))
        $page = Zend_Registry::get('page');

?>
<!DOCTYPE html>
<html>
	<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Bootstrap::$pageTitle;?> - GiáSốMột.Com</title>
    <meta name="description" content="<?php echo Bootstrap::$pageDesc;?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery.js"></script>
    <link rel="shortcut icon" href="<?php echo ASSETS_CDN;?>/image/favicon.ico" type="image/x-icon">
    <link rel="icon" href="<?php echo ASSETS_CDN;?>/image/favicon.ico" type="image/x-icon">
    
    <link type="text/css" rel="stylesheet" href="<?php echo ASSETS_CDN;?>/css/gig_application_layout-v3.8.2-542dd861f3.css">

    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Deals from 50-90% off on Restaurants, Fitness, Travel, Shopping, Beauty, Spas, Holiday Gifts and more." name="description">


    <link type="text/css" rel="stylesheet" href="<?php echo ASSETS_CDN;?>/css//styles-2902cc5ab3.css">
    <link href="<?php echo ASSETS_CDN;?>/css/styles-4afbab78a0.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo ASSETS_CDN;?>/css/facebook.css" rel="stylesheet" type="text/css" />

    
<?php //if (APPLICATION_ENV == 'development') :?>
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" >
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/reset.css" media="screen" rel="stylesheet" type="text/css" >
    
	<link href="<?php echo ASSETS_CDN;?>/css/styles-1a3ad22217.css" media="screen" rel="stylesheet" type="text/css" >
	<link href="<?php echo ASSETS_CDN;?>/css/styles-4f5ae5533f.css" media="screen" rel="stylesheet" type="text/css" >
	<link href="<?php echo ASSETS_CDN;?>/css/styles-6e7d0d401d.css" media="screen" rel="stylesheet" type="text/css" >
	<link href="<?php echo ASSETS_CDN;?>/css/styles-48b2ea4920.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/resources/css/jquery.toastmessage.css" rel="stylesheet" type="text/css"/>	
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/common.css" media="screen" rel="stylesheet" type="text/css" >
<?php 
$format = "DD/MM/YYYY";
?>

<script type='text/javascript'>
<?php echo $this->render('widget/php-to-js.phtml');?>
CL.DATE_FORMAT = "<?php echo substr(strtolower($format), 0, -2);?>";
</script>
	
</head>
<body class='prom-night ltr en_US en_XX'> 
<div id="global-container" style="display: block;">
<?php echo $this->render("gt_menu.phtml");?>
     <?php echo $this->layout()->content; ?>
<?php /*
</div>
*/?>
     
<footer class="footer-i18n">
    <div class="row">
        <div class="columns nine footer-i18n-payload">
			  <div class="row  footer-i18n-flexLinks">
	              <div class="columns four footer-links">
	                <h6 style='font-size: 15px;' class="footer-link-headline">Chính sách</h6>
	                <a title="" href="/term/ve-chung-toi">Về chúng tôi</a>
	                <a title="" href="/term/hinh-thuc-thanh-toan">Hình thức thanh toán</a>
	                <a title="" href="/term/chinh-sach-van-chuyen">Chính sách vận chuyển</a>
	                <a title="" href="/term/chinh-sach-doi-tra-hang">Chính sách đổi trả hàng</a>
	            	</div>
            	<div class="columns four footer-links">
	                <h6 style='font-size: 15px;' class="footer-link-headline">Hợp tác với GiaSoMot.vn</h6>
	                  <a title="Trợ giúp khách hàng" href="/term/tro-giup-khach-hang">Trợ giúp khách hàng</a>
	                <a title="Câu hỏi thường gặp" href="/term/cau-hoi-thuong-gap">Câu hỏi thường gặp</a>
	                <a title="Hợp tác với chúng tôi" href="/term/hop-tac-voi-chung-toi">Hợp tác với chúng tôi</a>
	                <a title="Quy trình đặt cọc" href="/term/quy-trinh-dat-coc">Quy trình đặt cọc</a>
	            	</div>
	            <div class="columns four footer-links">
	                <h6 style='font-size: 15px;' class="footer-link-headline">Thông tin</h6>
	                  <a title="Địa chỉ liên hệ" href="#">
	                  <?php /*
	                  Số 25, Ngõ 7, 
	                  */?>
	                  Phố Mễ Trì, Từ Liêm, Hà Nội</a>
	                <a title="Số điện thoại" href="#">(046).328.7272</a>
	                <a title="Hotline" href="#">0943.959.698</a>
           		  </div>
  			</div>
  			
  			<div class="row footer-i18n-sitemap border-footer-gsm" style='margin-bottom: 5px;'>
  				<?php /*
  				<div class="box_social">
		            <ul>
		                <li><a title="Tìm Giá Số Một trên Facebook" 
		                	href="http://www.facebook.com/giasomot">
		                		<img alt="" src="<?php echo ASSETS_CDN. '/somacro/noborder/facebook500.png'?>"
		                		width='37px'>
	                		</a></li>
		                <li><a title="Kênh Youtube - Giá Số Một" 
		                	href="http://www.youtube.com/giasomot">
		                		<img alt="" src="<?php echo ASSETS_CDN. '/somacro/noborder/youtube.png'?>"
		                		width='37px'>
                			</a></li>
		                <li><a title="Khách hàng góp ý" 
		                	href="/feedback/new">
		                		<img alt="" src="<?php echo ASSETS_CDN. '/somacro/noborder/user-comments-icon.png'?>"
		                		width='42px'>
	                		</a></li>
		            </ul>
		        </div>
  				*/?>
  			</div>
			  			
            <div class="row">
                <div class="columns twelve footer-i18n-seo">
  
                    <div class="footer-copyright">
                        &copy; 2014 giasomot, Inc.
              				All Rights Reserved.
                        <span class="footer-copyright-links">
                                <a style='text-decoration: none' 
                                	title="Bảo vệ riêng tư" href="/term/privacy">Bảo vệ riêng tư</a>
                                <a style='text-decoration: none' 
                                	title="Điều khoản sử dụng" href="/term/terms">Điều khoản sử dụng</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
  
        <div class="columns three footer-i18n-promos">
          <a title="giasomot for mobile devices" class="footer-i18n-promo footer-i18n-promo-mobile"
           href="#">
              <h6 class="footer-cta-headline">Get the GiaSoMot Mobile App 
              	<i class="icon-arrow-right-large"></i></h6>
            </a>
        </div>
  
    </div>
  
  </footer>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery-ui-1.8.16.custom.min.js"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/javascript/jquery.toastmessage.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/3rdparty/underscore-min.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/utils.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.form.js" type="text/javascript"></script>
    <?php /***********JQUERY*************/?>
    <script src="<?php echo ASSETS_CDN;?>/js/en.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/site.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/vi.js"></script>
    <?php /*
    */?>
    
    <?php /***********HOME ASSETS*************/?>
    <link href="<?php echo ASSETS_CDN;?>/css/styles.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo ASSETS_CDN;?>/css/gig_application_layout-v3.css" media="screen" rel="stylesheet" type="text/css" >
    
    
    <script type="text/javascript" src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/src/jquery.tokeninput.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/styles/token-input-facebook.css" />
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax_metadata_config.js" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo ASSETS_CDN;?>/tinymce/tinymce_3.5.2/jscripts/tiny_mce/tiny_mce.js"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/comment.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.ui.datepicker.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/autoresize.jquery.js" type="text/javascript"></script>
    
    <?php /*************SLIDER BRAND Thuong hieu****************/?>
    <link rel="stylesheet" type="text/css" href="<?php echo ASSETS_CDN;?>/Elastislide/css/demo.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo ASSETS_CDN;?>/Elastislide/css/elastislide.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo ASSETS_CDN;?>/Elastislide/css/custom.css" />
	<script src="<?php echo ASSETS_CDN;?>/Elastislide/js/modernizr.custom.17475.js"></script>
	
	<script type="text/javascript" src="<?php echo ASSETS_CDN;?>/Elastislide/js/jquerypp.custom.js"></script>
	<script type="text/javascript" src="<?php echo ASSETS_CDN;?>/Elastislide/js/jquery.elastislide.js"></script>
	<script type="text/javascript">
		$('#carousel').elastislide({
			minItems : 10
		});

		$(window).scroll(function() {
		    var height = $(window).scrollTop();

		    if(height  > 66) {
		        $('.nav-scroll-top-gt').css({
		        	margin: '-19px auto'
	        	});
		    }else{
		    	$('.nav-scroll-top-gt').css({
			        	margin: '0'
	        	});
	    	}
		});
	</script>
	
	<?php /*********SLIDER HOME*****************/?>
	<link rel="stylesheet" href="<link rel="stylesheet" type="text/css" href="<?php echo ASSETS_CDN;?>/Slidorion-master/css/style.css" />
	<link rel="stylesheet" href="<?php echo ASSETS_CDN;?>/Slidorion-master/css/slidorion.css" />
	<script src="<?php echo ASSETS_CDN;?>/Slidorion-master/js/jquery.easing.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/Slidorion-master/dist/jquery.slidorion.min.js"></script>

    <script>
	$(function(){
		$('#slidorion').slidorion({
			effect: 'slideRandom',
			hoverPause: true,
			interval: 20000,
			speed: 800,
			controlNav: false,
			controlNavClass: 'nav'
		});
	});
	</script>
	
	 <script type="text/javascript">
      window.fbAsyncInit = function() {
        // init the FB JS SDK
        FB.init({
          appId      : '7829106395',
          channelUrl : '' + window.location.protocol + '//' + window.location.host + '/facebook/xd_receiver.html',
          status     : true,
          xfbml      : true
        });
      };
    
      // Load the SDK asynchronously
      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/all.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
	
<?php echo $this->headScript();?>
<?php print $this->inlineScript();?>
</body>
</html>

