<?$base = '/rage/';?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Rage Maker</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="<?echo $base;?>css/jquery-ui.css?v=1.0.1" type="text/css" />

<script type="text/javascript" src="<?echo $base;?>js/jquery/jquery.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>js/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jQuery.cssTransform.Patch.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/cp_depends.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/excanvas.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/CanvasWidget.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/CanvasPainter.full.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.batchImageLoad.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.autogrow.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.flickr-1.0-min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/interface.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.blockUI.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/colorpicker.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.repeatedclick.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.imgDrop.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/jquery.getimagedata.min.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/base64.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/canvas2image.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/meme.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/site.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/rage.unmin.js"></script>
<script type="text/javascript" src="/site/rage-translations"></script>

<script type="text/javascript">
function capitaliseFirstLetter(string)
{
    return string.charAt(0).toUpperCase() + string.slice(1);
}

var t = function(str, format)
{
    var r = str;
    if (typeof rageTranslations[str] != 'undefined')
        r = rageTranslations[str]; 
    //convert to Capital letter
    if (typeof format != 'undefined' && format == 1)
        return capitaliseFirstLetter(r); 
    else
        return r;
};
var edit = false;
var img_url = '';
</script>

<script type="text/javascript">
<?php if($story != ''):?>
$(document).ready(function(){
    $("#rage-help").click(function(e) {
        $('html, body').scroll({
            scrollTop: $("#help-box").offset().top
        },500);
    });
});
<?php endif;?>
</script>
<script type="text/javascript" src="<?echo $base;?>js/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="<?echo $base;?>ragecomic/scripts/validate.js"></script>
<link href="<?echo $base;?>ragecomic/css/style.css?v=1.0.0" rel="stylesheet" type="text/css" />
<link href="<?echo $base;?>ragecomic/css/rage.css" rel="stylesheet" type="text/css" />
<link href="<?echo $base;?>ragecomic/css/meme.css" rel="stylesheet" type="text/css" />
<link href="<?echo $base;?>ragecomic/css/colorpicker.css?v=1.0.0" rel="stylesheet" type="text/css" />
<link href="<?echo $base;?>ragecomic/css/start/jquery-ui-1.7.2.custom.css?v=1.0.0" rel="stylesheet" type="text/css" />

</head>
<body class="MEME">
<?php echo $this->render("rage_menu.phtml");?>       
<?php echo $this->layout()->content;?>
</body>
</html>
